import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('flexible import detects title rows, accepts defaults and corrections, blocks repeat',async({page})=>{
 await page.route('https://auth.example.test/**',async route=>{const path=new URL(route.request().url()).pathname;await route.fulfill({json:path.endsWith('/token')?{token:'browser-test-token'}:{user:{id:'browser-user',name:'Browser',email:'browser@example.test',emailVerified:true},session:{id:'browser-session',userId:'browser-user',token:'browser-test-token',expiresAt:new Date(Date.now()+3600000).toISOString()}}})});
 const company=await (await page.request.post('/api/workspace/companies',{headers:{Authorization:'Bearer browser-test-token'},data:{name:'Importação flexível '+Date.now()}})).json();
 await page.addInitScript(id=>localStorage.setItem('lucra-company:browser-user',id),company.id);
 await page.goto('/#/workspace/imports');
 await expect(page.getByRole('heading',{name:'Da planilha para a gestão.'})).toBeVisible();
 const buffer=Buffer.from('Catálogo;;;;\n;;;;\nCód;Produto;Custo Aquisição;Preço Venda\nFLEX-1;Caneca;erro;25,90');
 await page.getByLabel('Escolha a planilha').setInputFiles({name:'flex.csv',mimeType:'text/csv',buffer});
 await expect(page.getByText('Ajustar leitura do arquivo (avançado)',{exact:true})).toBeVisible();
 await expect(page.getByLabel('Linha do cabeçalho')).toHaveValue('3');
 for(const width of [1440,820,360]){await page.setViewportSize({width,height:1000});expect(await page.locator('.import-column').evaluateAll(cards=>cards.every(card=>{const title=card.querySelector('.import-field-heading')!.getBoundingClientRect();const field=card.querySelector('select')!.getBoundingClientRect();return field.top-title.bottom>=12}))).toBeTruthy();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()}
 await page.setViewportSize({width:1440,height:1100});
 await page.screenshot({path:'output/review/import-simple-mapping.png',fullPage:true});
 await page.getByLabel('Valor fixo: Categoria',{exact:true}).fill('Casa');
 await page.getByRole('button',{name:'Validar e visualizar'}).click();
 await expect(page.getByRole('alert')).toContainText('Linha 4');
 await page.getByText('Corrigir valores por linha ou excluir totais do lote',{exact:true}).click();
 await page.getByRole('region',{name:'Revisão editável'}).locator('tbody td').nth(4).locator('input').fill('10,50');
 await page.getByRole('button',{name:'Validar correções'}).click();
 await expect(page.getByRole('button',{name:'Confirmar importação'})).toBeEnabled();
 const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa']).analyze();expect(axe.violations).toEqual([]);
 await page.screenshot({path:'output/review/import-flexible.png',fullPage:true});
 await page.getByRole('button',{name:'Confirmar importação'}).click();
 await expect(page.getByRole('status')).toContainText('1 registros importados');
 await page.getByRole('button',{name:'Ler este arquivo para Produtos'}).click();
 await page.getByLabel('Valor fixo: Categoria',{exact:true}).fill('Casa');
 await page.getByRole('button',{name:'Validar e visualizar'}).click();
 await page.getByText('Corrigir valores por linha ou excluir totais do lote',{exact:true}).click();
 await page.getByRole('region',{name:'Revisão editável'}).locator('tbody td').nth(4).locator('input').fill('10,50');
 await page.getByRole('button',{name:'Validar correções'}).click();
 await expect(page.getByRole('alert')).toContainText('Já cadastrados');
 await expect(page.getByRole('button',{name:'Confirmar importação'})).toBeDisabled();
});
