import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('integrated sale updates stock, receipts, returns and simulator',async({page})=>{
 test.setTimeout(60000);
 await page.route('https://auth.example.test/**',route=>route.fulfill({json:new URL(route.request().url()).pathname.endsWith('/token')?{token:'browser-test-token'}:{user:{id:'trading-user',email:'trading@example.test',emailVerified:true},session:{id:'trading-session',userId:'trading-user',token:'opaque',expiresAt:new Date(Date.now()+3600000).toISOString()}}}));
 const headers={Authorization:'Bearer browser-test-token'};
 const c=await (await page.request.post('/api/workspace/companies',{headers,data:{name:'Loja integrada'}})).json();
 const base='/api/workspace/'+c.id;
 const p=await (await page.request.post(base+'/records/products',{headers,data:{name:'Tênis integrado',sku:'INT1',category:'Calçados',unit_cost:10000,unit_price:18000}})).json();
 await page.request.post(base+'/records/stock_movements',{headers,data:{product_id:p.id,direction:'in',quantity:10,reference:'INITIAL',occurred_on:'2026-01-01',description:'Inicial'}});
 await page.addInitScript(id=>localStorage.setItem('lucra-company:trading-user',id),c.id);
 await page.goto('/#/workspace/sales');
 await page.getByRole('button',{name:'Adicionar venda',exact:true}).click();
 await page.getByLabel('Produto 1',{exact:true}).selectOption(p.id);
 await expect(page.getByLabel('Preço 1',{exact:true})).toHaveValue('180');
 await page.getByLabel('Quantidade 1',{exact:true}).fill('2');
 await page.getByRole('button',{name:'Confirmar venda',exact:true}).click();
 await expect(page.locator('.workspace-notice')).toContainText('Venda registrada');
 await page.getByRole('button',{name:'Valores a receber',exact:true}).click();
 await expect(page.getByText('R$ 360,00 em aberto',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Receber',exact:true}).click();
 await page.getByLabel('Valor recebido (R$)').fill('100');
 await page.getByRole('button',{name:'Salvar',exact:true}).click();
 await expect(page.getByText('R$ 260,00 em aberto',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Devolver / cancelar',exact:true}).click();
 await page.getByLabel('Quantidade devolvida').fill('1');
 await page.getByLabel('Motivo').fill('Cliente devolveu uma unidade');
 await page.getByRole('button',{name:'Salvar',exact:true}).click();
 await expect(page.getByText('1 un. devolvidas',{exact:true})).toBeVisible();
 await expect(page.getByText('R$ 80,00 em aberto',{exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Estoque',exact:true}).click();
 await expect(page.getByText('9 un.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Limites',exact:true}).click();
 await page.getByLabel('Estoque mínimo').fill('10');await page.getByLabel('Estoque máximo').fill('30');
 await page.getByRole('button',{name:'Salvar',exact:true}).click();
 await expect(page.getByText('Abaixo do mínimo',{exact:true}).last()).toBeVisible();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar Excel',exact:true}).click();expect((await download).suggestedFilename()).toBe('estoque-lucra.xlsx');
 await page.getByRole('button',{name:'Movimentações',exact:true}).click();
 await expect(page.getByRole('cell',{name:'Cliente devolveu uma unidade',exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Simulador de preço',exact:true}).click();
 await page.getByLabel('Produto 1',{exact:true}).selectOption(p.id);
 await page.getByLabel('Preço 1',{exact:true}).fill('80');
 await expect(page.getByText(/Esta venda gera prejuízo/)).toBeVisible();
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa']).analyze()).violations).toEqual([]);
 expect((await (await page.request.get(base+'/records/sales',{headers})).json()).length).toBe(1);
});
