import {gunzipSync} from 'node:zlib';
import {readFileSync} from 'node:fs';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('demo adapts to phone and desktop, changes period and exports PDF',async({page})=>{
 await page.goto('/#/demo/overview');
 await expect(page.getByText('R$ 150.000,00',{exact:true}).first()).toBeVisible();
 for(const width of [360,768,1440]){
  await page.setViewportSize({width,height:1000});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 }
 const download=page.waitForEvent('download');
 await page.getByRole('button',{name:'Exportar relatório',exact:true}).click();
 expect((await download).suggestedFilename()).toMatch(/\.pdf$/);
 await page.getByRole('button',{name:'Diário',exact:true}).click();
 await expect(page.getByText('R$ 150.000,00',{exact:true})).toHaveCount(0);
});

test('workspace persists company, stock, bills, CSV and PDF; accessible on mobile',async({page})=>{
 test.setTimeout(60000);
 await page.route('https://auth.example.test/**',async route=>{
  const path=new URL(route.request().url()).pathname;
  const body=path.endsWith('/token')?{token:'browser-test-token'}:{
   user:{id:'browser-user',name:'Browser',email:'browser@example.test',emailVerified:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},
   session:{id:'browser-session',userId:'browser-user',token:'browser-test-token',expiresAt:new Date(Date.now()+3600000).toISOString()}
  };
  await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});
 });
 await page.goto('/#/workspace/dashboard');
 await expect(page.getByRole('heading',{name:'Painel de controle',exact:true})).toBeVisible();
 await expect(page.getByText('Carregando sua empresa…',{exact:true})).toHaveCount(0);
 if(!await page.getByLabel('Nome da empresa').isVisible()){await page.getByRole('link',{name:'Configurações',exact:true}).click();await page.getByText('Cadastrar outra empresa',{exact:true}).click();}
 await page.getByLabel('Nome da empresa').fill('Empresa de teste navegador');
 await page.getByRole('button',{name:'Criar empresa',exact:true}).click();
 await page.goto('/#/workspace/dashboard');
 await expect(page.getByRole('heading',{name:'Da receita ao resultado'})).toBeVisible();
 await page.getByRole('link',{name:'Integrações',exact:true}).first().click();
 await page.getByText('Cadastrar origem de dados',{exact:true}).click();
 await page.getByLabel('Nome da origem').fill('ERP teste');
 await page.getByLabel('Sistema / fornecedor').fill('Arquivo do ERP');
 await page.getByRole('button',{name:'Salvar origem'}).click();
 await expect(page.getByRole('heading',{name:'ERP teste',exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Produtos',exact:true}).click();
 await page.getByRole('button',{name:'Adicionar produto',exact:true}).click();
 await page.getByLabel('SKU',{exact:true}).fill('SKU-001');
 await page.getByLabel('Produto',{exact:true}).fill('Caneca');
 await page.getByLabel('Categoria',{exact:true}).fill('Casa');
 await page.getByLabel('Custo unitário (R$)').fill('10');
 await page.getByLabel('Preço unitário (R$)').fill('20');
 await page.getByLabel('Observações',{exact:true}).fill('Embalagem individual');
 await page.getByRole('button',{name:'Salvar produto',exact:true}).click();
 await expect(page.getByRole('cell',{name:'Caneca',exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Estoque',exact:true}).first().click();
 await page.getByRole('button',{name:'Movimentar estoque',exact:true}).click();
 await page.getByRole('combobox',{name:'Produto',exact:true}).selectOption({label:'Caneca · SKU-001'});
 await page.getByLabel('Quantidade',{exact:true}).fill('5');
 await page.getByLabel('Motivo').fill('Saldo inicial');
 await page.getByRole('button',{name:'Salvar',exact:true}).click();
 await expect(page.locator('.workspace-notice')).toContainText('Estoque atualizado');
 await expect(page.getByText('5 un.',{exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Contas a pagar',exact:true}).first().click();
 await page.getByRole('button',{name:'Adicionar conta',exact:true}).click();
 await page.getByLabel('Para quem? (fornecedor)').fill('Imobiliária');
 await page.getByLabel('O que vai pagar?').fill('Aluguel');
 await page.getByLabel('Categoria',{exact:true}).fill('Fixa');
 await page.getByLabel('Valor da conta (R$)',{exact:true}).fill('100');
 await page.getByRole('button',{name:'Salvar',exact:true}).click();
 await expect(page.locator('.workspace-notice')).toContainText('Salvo');
 await page.getByRole('button',{name:'Registrar pagamento',exact:true}).click();
 await page.getByLabel('Valor pago (R$)').fill('30');
 await page.getByRole('button',{name:'Salvar',exact:true}).click();
 await expect(page.getByRole('cell',{name:'R$ 70,00',exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Vendas',exact:true}).first().click();
 await page.getByRole('button',{name:'Adicionar venda',exact:true}).click();
 await page.getByLabel('Produto 1',{exact:true}).selectOption({label:'Caneca · SKU-001'});
 await page.getByLabel('Preço 1',{exact:true}).fill('25');
 await page.getByRole('button',{name:'Confirmar venda',exact:true}).click();
 await expect(page.locator('.workspace-notice')).toContainText('Venda registrada');
 await expect(page.getByRole('cell',{name:'R$ 25,00',exact:true}).first()).toBeVisible();
 await page.getByRole('link',{name:'Configurações',exact:true}).first().click();
 await page.getByRole('link',{name:'Configurar taxas e parcelamento'}).click();
 await page.getByRole('button',{name:'Adicionar condição',exact:true}).click();
 await page.getByLabel('Nome da condição').fill('Cartão 6x');
 await page.getByLabel('Parcelas',{exact:true}).fill('6');
 await page.getByLabel('Cartão / MDR (%)').fill('2.5');
 await page.getByRole('button',{name:'Salvar condição',exact:true}).click();
 await expect(page.getByRole('cell',{name:'Cartão 6x',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Editar Cartão 6x',exact:true}).click();
 await page.getByLabel('Cartão / MDR (%)').fill('3');
 await page.getByRole('button',{name:'Salvar alterações',exact:true}).click();
 await expect(page.getByRole('status').filter({hasText:'Registro salvo'})).toBeVisible();
 await page.getByRole('link',{name:'Importações',exact:true}).first().click();
 await page.getByText('Origem e integrações (opcional)',{exact:true}).click();
 await page.getByLabel('Origem dos dados').selectOption({label:'ERP teste'});
 await page.getByLabel('O que deseja importar?').selectOption('sales');
 const csv='external_id,sold_on,product,category,quantity,revenue,cmv,tax,card,commission,installments\nVENDA-001,2026-09-18,Caneca,Casa,1,20.00,10.00,1.00,0.50,1.00,1\n';
 await page.getByLabel('Escolha a planilha').setInputFiles({name:'vendas.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});
 await page.getByText('Salvar relação de colunas para reutilizar',{exact:true}).click();
 if(await page.getByLabel('Nome do mapeamento').isVisible()){
  await page.getByLabel('Nome do mapeamento').fill('Colunas vendas');
  await page.getByRole('button',{name:'Salvar mapeamento'}).click();
  await expect(page.getByRole('status')).toContainText('Mapeamento salvo');
 }
 await page.getByRole('button',{name:'Validar e visualizar'}).click();
 await page.getByRole('button',{name:'Confirmar importação'}).click();
 await expect(page.getByRole('status').filter({hasText:'1 registros importados com sucesso'})).toBeVisible();
 await page.getByRole('link',{name:'Relatórios',exact:true}).first().click();
 const download=page.waitForEvent('download');
 await page.getByRole('button',{name:'Gerar e salvar PDF'}).click();
 expect((await download).suggestedFilename()).toMatch(/\.pdf$/);
 await page.reload();
 await expect(page.getByRole('button',{name:'Baixar PDF',exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Painel de controle',exact:true}).click();
 await expect(page.getByRole('heading',{name:'O que merece atenção'})).toBeVisible();
 await expect(page.getByRole('navigation',{name:'Operações desta área'})).toHaveCount(0);
 await expect(page.getByRole('heading',{name:'Produtos e margens',exact:true})).toBeVisible();
 await expect(page.getByRole('region',{name:'Gráfico de formação do resultado'})).not.toBeVisible();
 await page.locator('.panel-financial-details > summary').click();
 await expect(page.getByRole('region',{name:'Gráfico de formação do resultado'})).toBeVisible();
 await page.locator('.panel-financial-details > summary').click();
 await page.getByRole('combobox',{name:'Ordenar por'}).selectOption('loss');
 await page.getByLabel('Buscar produto',{exact:true}).fill('Caneca');
 await expect(page.getByRole('region',{name:'Desempenho de produtos'}).getByRole('cell',{name:'Caneca',exact:true})).toBeVisible();
 await page.getByLabel('Buscar produto',{exact:true}).fill('');
 await page.getByRole('combobox',{name:'Período',exact:true}).selectOption('weekly');
 const panelDownload=page.waitForEvent('download');
 await page.getByRole('button',{name:'Exportar relatório',exact:true}).click();
 expect((await panelDownload).suggestedFilename()).toMatch(/\.pdf$/);
 await page.getByRole('combobox',{name:'Período',exact:true}).selectOption('monthly');
 await expect(page.getByRole('button',{name:'Criar empresa',exact:true})).toHaveCount(0);
 await expect(page.getByRole('combobox',{name:'Sua empresa',exact:true})).toHaveCount(0);
 for(const width of [360,768,1440,2560]){
  await page.setViewportSize({width,height:1000});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  if(width===2560){
   const bounds=await page.locator('#workspace-main').boundingBox();
   expect(bounds!.width).toBeGreaterThan(2200);
   await page.screenshot({path:'output/analysis-wide.png',fullPage:true});
  }
 }
 await page.setViewportSize({width:1440,height:1000});
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa']).analyze()).violations).toEqual([]);
 await page.screenshot({path:'output/analysis-desktop.png',fullPage:true});
 await page.getByRole('link',{name:'Planos de ação',exact:true}).click();
 await page.getByText('Criar plano de ação',{exact:true}).click();
 await page.getByLabel('Título do plano').fill('Revisar preços');
 await page.getByLabel('Objetivo').fill('Aumentar a margem');
 await page.getByRole('button',{name:'Salvar plano'}).click();
 await expect(page.getByRole('heading',{name:'Revisar preços',exact:true})).toBeVisible();
 await page.getByLabel('Resposta ou atualização').fill('Preço revisado com a equipe.');
 await page.getByRole('button',{name:'Registrar no histórico'}).click();
 await expect(page.getByText('Preço revisado com a equipe.',{exact:true})).toBeVisible();
 await page.getByLabel('Andamento').selectOption('done');
 await expect(page.getByText('Concluído',{exact:true}).first()).toBeVisible();
 await page.getByRole('link',{name:'Importações',exact:true}).first().click();
 await page.getByLabel('Escolha a planilha').setInputFiles('tests/fixtures/products.xlsx');
 await page.getByRole('button',{name:'Validar e visualizar'}).click();
 await page.getByRole('button',{name:'Confirmar importação'}).click();
 await expect(page.getByRole('status')).toContainText('1 registros importados');
 await page.getByRole('link',{name:'Produtos',exact:true}).first().click();
 await expect(page.getByRole('cell',{name:'Produto Excel',exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Clientes',exact:true}).click();
 await page.getByText('Cadastrar cliente',{exact:true}).click();
 await page.setViewportSize({width:360,height:900});
 await page.screenshot({path:'output/review/customer-form-360.png'});
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa']).analyze()).violations).toEqual([]);
 await page.setViewportSize({width:1440,height:960});
 await page.screenshot({path:'output/review/customer-form-1440.png'});
 await page.getByLabel('Nome do cliente').fill('Cliente exemplo');
 await page.getByLabel('Telefone',{exact:true}).fill('11987654321');
 await expect(page.getByLabel('Telefone',{exact:true})).toHaveValue('(11) 98765-4321');
 await page.getByLabel('CPF/CNPJ',{exact:true}).fill('12345678000190');
 await expect(page.getByLabel('CPF/CNPJ',{exact:true})).toHaveValue('12.345.678/0001-90');
 await page.getByLabel('CPF/CNPJ',{exact:true}).fill('12345678900');
 await expect(page.getByLabel('CPF/CNPJ',{exact:true})).toHaveValue('123.456.789-00');
 await page.getByLabel('Chave PIX',{exact:true}).fill('cliente@example.test');
 await page.getByLabel('Endereço',{exact:true}).fill('Rua Um, 10');
 await page.getByLabel('Cidade',{exact:true}).fill('Manaus');
 await page.getByLabel('Observações',{exact:true}).fill('Cliente prefere telefone');
 await page.getByRole('button',{name:'Salvar cliente'}).click();
 await expect(page.getByText('Cliente prefere telefone',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Editar cadastro',exact:true}).click();
 await expect(page.getByLabel('Telefone',{exact:true})).toHaveValue('(11) 98765-4321');
 await expect(page.getByLabel('CPF/CNPJ',{exact:true})).toHaveValue('123.456.789-00');
 await page.getByLabel('Cidade',{exact:true}).fill('Belém');
 await page.getByRole('button',{name:'Salvar alterações',exact:true}).click();
 await expect(page.getByText('Belém',{exact:true}).last()).toBeVisible();
 await expect(page.getByRole('heading',{name:'Cliente exemplo',exact:true})).toBeVisible();
 await page.getByLabel('Contato realizado').fill('Consulta sobre reposição');
 await page.getByLabel('Resposta do cliente').fill('Retorna na próxima semana');
 await page.getByLabel('Próximo retorno').fill('2026-09-30');
 await page.getByRole('button',{name:'Registrar no histórico'}).click();
 await expect(page.getByText('Retorna na próxima semana',{exact:true})).toBeVisible();
 await page.reload();
 await expect(page.getByText('Retorna na próxima semana',{exact:true})).toBeVisible();
 for(const width of [360,768,1440]){
  await page.setViewportSize({width,height:900});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 }
 await page.getByRole('link',{name:'Integrações',exact:true}).first().click();
 await expect(page.getByRole('cell',{name:'Importado',exact:true}).first()).toBeVisible();
 await page.getByRole('link',{name:'Backups',exact:true}).click();
 const backupDownload=page.waitForEvent('download');
 await page.getByRole('button',{name:'Baixar backup da empresa'}).click();
 const backup=await backupDownload;
 expect(backup.suggestedFilename()).toMatch(/\.json\.gz$/);
 const snapshot=JSON.parse(gunzipSync(readFileSync((await backup.path())!)).toString());
 expect(snapshot.format).toBe('lucra-company');
 expect(snapshot.records.products).toHaveLength(2);
 expect(snapshot.records.products.find((p:any)=>p.sku==='SKU-001').notes).toBe('Embalagem individual');
 expect(snapshot.records.customers[0].city).toBe('Belém');
 expect(snapshot.records.customers[0].pix_key).toBe('cliente@example.test');
 expect(snapshot.records.customer_contacts[0].response).toBe('Retorna na próxima semana');
 expect(snapshot.records.import_jobs.some((j:any)=>j.status==='imported')).toBeTruthy();
 await expect(page.getByRole('status')).toContainText('Cópia gerada');
 await page.setViewportSize({width:360,height:800});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
 expect(results.violations).toEqual([]);
});
