"""Natural-language analysis of one company's data, generated by Sobrevo itself.

The backend assembles a bounded dossier of the company's numbers under the
caller's RLS identity and `insights.analyze` turns it into a written answer
with built-in rules and templates. No external service is called and no data
leaves the system. Answers are stored append-only (assistant_reports) and
exported to PDF.
"""
from datetime import date, timedelta
from typing import Literal
from uuid import UUID

from fastapi import Depends, HTTPException, Response
from pydantic import BaseModel, Field

from . import insights
from .finance import period_bounds
from .workspace import router, Input, Session, session, Period, company_summary, payables, inventory

# ---- Answer contract shared by the page and the PDF ----

class Highlight(BaseModel):
    label: str
    value: str
    trend: Literal['up', 'down', 'flat', 'none']
    note: str

class Section(BaseModel):
    heading: str
    paragraphs: list[str]
    bullets: list[str]

class Action(BaseModel):
    title: str = Field(max_length=160)
    description: str = Field(max_length=4000)
    priority: Literal['high', 'medium', 'low']

class Answer(BaseModel):
    title: str
    summary: str
    highlights: list[Highlight]
    sections: list[Section]
    actions: list[Action]
    caveats: list[str]

# ---- Dossier ----

def reais(cents):
    return round((cents or 0) / 100, 2)

MONEY_TOTALS = ('revenue', 'cmv', 'tax', 'card', 'commission', 'estimated', 'hidden', 'net', 'expenses', 'refunds', 'cost_recovered', 'operating')

def _period(summary):
    t = summary['totals']
    return {'inicio': summary['start'], 'fim': summary['end'], 'unidades_vendidas': t['quantity'],
            **{k: reais(t.get(k, 0)) for k in MONEY_TOTALS},
            'margem_vendas_pct': t['margin'], 'margem_operacional_pct': t.get('operating_margin', 0)}

def build_dossier(db, cid, period, anchor):
    """Everything the model may use, computed here under the caller's RLS identity."""
    company = db.company(cid)
    today = date.today()
    current = company_summary(db, cid, period, anchor)
    previous = company_summary(db, cid, period, period_bounds(period, anchor)[0] - timedelta(days=1))
    products = sorted(current['products'], key=lambda p: -p['revenue'])
    chosen = (products[:15] + [p for p in products[15:] if p['net'] < 0])[:30]
    start, end = period_bounds(period, anchor)
    expenses = db.query("select category,sum(amount)::bigint total from public.expenses where company_id=%s and incurred_on between %s and %s group by category order by total desc limit 15",
                        (cid, start, end))
    bills = payables(UUID(cid), db)
    open_bills = [b for b in bills if b['balance'] > 0]
    horizon = str(today + timedelta(days=30))
    stock = inventory(UUID(cid), db)
    from .trading import receivables
    parts = [(p, s) for s in receivables(UUID(cid), db) for p in s['parts'] if p['balance'] > 0]
    plans = db.rows('action_plans', cid)
    contacts = db.query("select count(*)::int due from public.customer_contacts where company_id=%s and next_on between %s and %s", (cid, today, today + timedelta(days=7)))
    customers = db.query('select count(*)::int total from public.customers where company_id=%s', (cid,))
    return {
        'empresa': company['name'], 'data_de_hoje': str(today), 'periodo_tipo': period,
        'periodo_atual': _period(current), 'periodo_anterior': _period(previous),
        'resultado_diario_atual': [{'data': d['date'], 'estimado': reais(d['estimated']), 'resultado': reais(d['net'])} for d in current['daily'] if d['estimated'] or d['net']],
        'produtos_no_periodo': [{'produto': p['name'], 'categoria': p['category'], 'parcelas': p['installments'], 'unidades': p['quantity'],
                                 'receita': reais(p['revenue']), 'resultado': reais(p['net']), 'margem_pct': p['margin']} for p in chosen],
        'produtos_com_prejuizo': sum(p['net'] < 0 for p in products),
        'despesas_por_categoria': [{'categoria': e['category'], 'total': reais(e['total'])} for e in expenses],
        'contas_a_pagar': {
            'saldo_em_aberto': reais(sum(b['balance'] for b in open_bills)),
            'vencidas': {'quantidade': sum(b['status'] == 'overdue' for b in open_bills), 'total': reais(sum(b['balance'] for b in open_bills if b['status'] == 'overdue'))},
            'proximos_30_dias': [{'fornecedor': b['supplier'], 'descricao': b['description'], 'vencimento': b['due_on'], 'saldo': reais(b['balance'])}
                                 for b in open_bills if b['status'] != 'overdue' and b['due_on'] <= horizon][:10]},
        'estoque': {
            'produtos': len(stock), 'unidades': sum(s['balance'] for s in stock), 'valor_ao_custo': reais(sum(s['balance'] * s['unit_cost'] for s in stock)),
            'sem_saldo': [s['name'] for s in stock if s['balance'] <= 0][:15],
            'abaixo_do_minimo': [{'produto': s['name'], 'saldo': s['balance'], 'minimo': s['min_stock']} for s in stock if 0 < s['balance'] < s['min_stock']][:15]},
        'a_receber': {
            'saldo_em_aberto': reais(sum(p['balance'] for p, _ in parts)),
            'vencido': reais(sum(p['balance'] for p, _ in parts if p['due_on'] and p['due_on'] < str(today))),
            'proximos_30_dias': reais(sum(p['balance'] for p, _ in parts if p['due_on'] and str(today) <= p['due_on'] <= horizon))},
        'planos_de_acao': {
            **{status: sum(p['status'] == status for p in plans) for status in ('pending', 'progress', 'done')},
            'atrasados': [p['title'] for p in plans if p['status'] != 'done' and p.get('due_on') and p['due_on'] < str(today)][:10],
            'em_aberto': [p['title'] for p in plans if p['status'] != 'done'][:10]},
        'clientes': {'cadastrados': customers[0]['total'], 'retornos_nos_proximos_7_dias': contacts[0]['due']},
    }

# ---- Routes ----

class Ask(Input):
    question: str = Field(min_length=3, max_length=1000)
    period: Period = 'monthly'
    anchor: date

@router.get('/{company_id}/assistant')
def assistant_overview(company_id: UUID, db: Session = Depends(session)):
    cid = str(company_id); db.company(cid)
    history = db.query("select id,question,period,anchor,created_at,answer->>'title' title from public.assistant_reports where company_id=%s order by created_at desc limit 30", (cid,))
    return {'history': history}

@router.post('/{company_id}/assistant', status_code=201)
def ask(company_id: UUID, body: Ask, db: Session = Depends(session)):
    cid = str(company_id); db.company(cid)
    dossier = build_dossier(db, cid, body.period, body.anchor)
    answer = Answer.model_validate(insights.analyze(dossier, body.question)).model_dump()
    return db.insert('assistant_reports', {'company_id': cid, 'question': body.question, 'period': body.period, 'anchor': str(body.anchor),
                                           'answer': answer, 'model': insights.ENGINE})

def _report(db, cid, report_id):
    rows = db.rows('assistant_reports', cid, id=f'eq.{report_id}')
    if not rows: raise HTTPException(404, 'Análise não encontrada.')
    return rows[0]

@router.get('/{company_id}/assistant/{report_id}')
def assistant_report(company_id: UUID, report_id: UUID, db: Session = Depends(session)):
    cid = str(company_id); db.company(cid)
    return _report(db, cid, report_id)

@router.get('/{company_id}/assistant/{report_id}/pdf')
def assistant_report_pdf(company_id: UUID, report_id: UUID, db: Session = Depends(session)):
    from .report import assistant_pdf
    cid = str(company_id); company = db.company(cid)
    record = _report(db, cid, report_id)
    start, end = period_bounds(record['period'], date.fromisoformat(record['anchor']))
    return Response(assistant_pdf(record, company['name'], start, end), media_type='application/pdf',
                    headers={'Content-Disposition': f'attachment; filename="analise-{record["anchor"]}-{str(report_id)[:8]}.pdf"'})
