import React,{useEffect,useRef,useState} from 'react';
import {Plus,Search,CheckCircle2,Clock,Flag,ListTodo,ArrowRight,X} from 'lucide-react';
import {Requester,Row} from './BusinessPages';
import './strategy.css';
const stages:Record<string,string>={pending:'A fazer',progress:'Em andamento',done:'Concluído'};
const priorities:Record<string,string>={high:'Alta',medium:'Média',low:'Baixa'};
const today=()=>new Date().toLocaleDateString('en-CA');
const dateText=(s:string)=>s?s.split('-').reverse().join('/'):'Sem prazo';
const overdue=(p:Row)=>p.status!=='done'&&p.due_on&&p.due_on<today();
const fields=(p:Row)=>({title:p.title,description:p.description||'',priority:p.priority,status:p.status,due_on:p.due_on||null});

export function ActionPlans({base,request}:{base:string;request:Requester}){
 const [rows,setRows]=useState<Row[]>([]),[entries,setEntries]=useState<Row[]>([]),[selected,setSelected]=useState(''),[edit,setEdit]=useState<Row|null>(null);
 const [query,setQuery]=useState(''),[priority,setPriority]=useState(''),[version,setVersion]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{let live=true;setLoading(true);setError('');Promise.all(['action_plans','plan_updates'].map(t=>request(base+'/records/'+t).then(r=>r.json()))).then(([r,e])=>{if(live){setRows(r);setEntries(e)}}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[base,version]);
 async function save(path:string,data:Row,method='POST'){setBusy(true);setError('');try{await request(base+'/records/'+path,{method,body:JSON.stringify(data)});setVersion(v=>v+1);setNotice('Alterações salvas.');return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 const visible=rows.filter(p=>(p.title+' '+p.description).toLocaleLowerCase().includes(query.toLocaleLowerCase())&&(!priority||p.priority===priority)).sort((a,b)=>Number(!!overdue(b))-Number(!!overdue(a))||['high','medium','low'].indexOf(a.priority)-['high','medium','low'].indexOf(b.priority)||(a.due_on||'9999').localeCompare(b.due_on||'9999'));
 const current=rows.find(p=>p.id===selected),history=entries.filter(e=>e.plan_id===selected).sort((a,b)=>b.created_at.localeCompare(a.created_at));
 const done=rows.filter(p=>p.status==='done').length;
 return <section className="action-studio" aria-busy={loading}>
  <div className="strategy-intro"><div><span className="eyebrow">DA PRIORIDADE AO RESULTADO</span><h2>Um próximo passo para cada melhoria.</h2><p>Você define o andamento: inicie quando começar e conclua quando terminar o objetivo.</p></div><button className="primary-button" onClick={()=>setEdit({status:'pending',priority:'medium'})}><Plus size={17}/>Novo plano</button></div>
  <div className="plan-metrics">{[[ListTodo,'A fazer',rows.filter(p=>p.status==='pending').length],[Clock,'Em andamento',rows.filter(p=>p.status==='progress').length],[Flag,'Prazo vencido',rows.filter(overdue).length],[CheckCircle2,'Concluídos',done]].map(([Icon,label,value]:any)=><article key={label}><Icon size={20}/><div><strong>{value}</strong><span>{label}</span></div></article>)}</div>
  {error&&<div className="workspace-error" role="alert">{error}<button onClick={()=>setVersion(v=>v+1)}>Tentar novamente</button></div>}{notice&&<p role="status" className="workspace-notice">{notice}</p>}
  <div className="plan-filter"><label><Search size={17}/><input aria-label="Buscar plano" placeholder="Buscar objetivo ou ação…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Prioridade<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">Todas</option>{Object.entries(priorities).map(([v,t])=><option value={v} key={v}>{t}</option>)}</select></label><span>{done} de {rows.length} concluídos</span></div>
  {loading?<p role="status">Carregando seus planos…</p>:!rows.length&&!error?<div className="plan-welcome"><ListTodo size={36}/><h2>Transforme uma ideia em uma ação.</h2><p>Comece com um objetivo concreto, como revisar preços ou organizar os pagamentos da semana.</p><button className="primary-button" onClick={()=>setEdit({status:'pending',priority:'medium'})}>Criar primeiro plano</button><a href="#/workspace/analysis">Ver recomendações do painel <ArrowRight size={15}/></a></div>:<div className="plan-board">{Object.entries(stages).map(([status,title])=><section className={'plan-column '+status} key={status} aria-label={title}><header><h3>{title}</h3><span>{visible.filter(p=>p.status===status).length}</span></header>{visible.filter(p=>p.status===status).map(p=><article className="plan-card" key={p.id}><button className="plan-tile" onClick={()=>setSelected(p.id)}><span className={'plan-priority '+p.priority}>Prioridade {priorities[p.priority].toLowerCase()}</span><strong>{p.title}</strong><p>{p.description||'Abra para detalhar o objetivo e registrar o acompanhamento.'}</p><footer><span className={overdue(p)?'plan-overdue':''}>{overdue(p)?'Vencido · ':''}{dateText(p.due_on)}</span><span>{entries.filter(e=>e.plan_id===p.id).length} atualizações</span></footer><span className="plan-open-hint">Ver detalhes e histórico →</span></button><div className="plan-card-actions"><button className={p.status==='done'?'':'primary-button'} disabled={busy} onClick={()=>save('action_plans/'+p.id,{...fields(p),status:p.status==='pending'?'progress':p.status==='progress'?'done':'progress'},'PATCH')}>{p.status==='pending'?'Iniciar plano':p.status==='progress'?'Marcar como concluído':'Reabrir plano'}</button></div></article>)}{!visible.some(p=>p.status===status)&&<p className="plan-column-empty">{query||priority?'Nenhum plano neste filtro.':'Nenhum plano nesta etapa.'}</p>}</section>)}</div>}
  {edit&&<PlanDialog plan={edit} busy={busy} error={error} onClose={()=>setEdit(null)} onSave={async values=>{if(await save('action_plans'+(edit.id?'/'+edit.id:''),values,edit.id?'PATCH':'POST'))setEdit(null)}}/>}
  {current&&!edit&&<PlanDetails key={current.id} plan={current} history={history} busy={busy} error={error} onClose={()=>setSelected('')} onEdit={()=>setEdit(current)} onStatus={status=>save('action_plans/'+current.id,{...fields(current),status},'PATCH')} onNote={message=>save('plan_updates',{plan_id:current.id,message})}/>}
 </section>
}
function PlanDialog({plan,busy,error,onClose,onSave}:{plan:Row;busy:boolean;error:string;onClose:()=>void;onSave:(p:Row)=>Promise<void>}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal()},[]);
 return <dialog ref={ref} className="catalog-dialog plan-dialog" aria-label={plan.id?'Editar plano':'Novo plano'} onCancel={e=>{e.preventDefault();if(!busy)onClose()}}><form className="catalog-form" onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));onSave({...f,status:plan.status,due_on:f.due_on||null})}}><div className="catalog-form-heading"><span className="eyebrow">PLANEJE COM CLAREZA</span><h2>{plan.id?'Editar plano':'O que você quer melhorar?'}</h2><p>Um objetivo específico torna o acompanhamento mais simples.</p></div><div className="catalog-fields"><label>Título do plano<input name="title" autoFocus required minLength={2} maxLength={160} defaultValue={plan.title} placeholder="Ex.: Revisar preços dos produtos com prejuízo"/></label><label>Objetivo e próximos passos<textarea name="description" maxLength={4000} rows={4} defaultValue={plan.description} placeholder="Descreva o resultado esperado e o que precisa ser feito."/></label><label>Prioridade<select name="priority" defaultValue={plan.priority}>{Object.entries(priorities).map(([v,t])=><option value={v} key={v}>{t}</option>)}</select></label><label>Prazo do plano<input type="date" name="due_on" defaultValue={plan.due_on||''}/></label></div>{error&&<p className="workspace-error" role="alert">{error}</p>}<div className="catalog-form-actions"><button type="button" disabled={busy} onClick={onClose}>Cancelar</button><button className="primary-button" disabled={busy}>{busy?'Salvando…':'Salvar plano'}</button></div></form></dialog>
}
function PlanDetails({plan,history,busy,error,onClose,onEdit,onStatus,onNote}:{plan:Row;history:Row[];busy:boolean;error:string;onClose:()=>void;onEdit:()=>void;onStatus:(s:string)=>Promise<boolean>;onNote:(s:string)=>Promise<boolean>}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal()},[]);
 return <dialog ref={ref} className="catalog-dialog plan-dialog plan-detail" aria-label="Acompanhar plano" onCancel={e=>{e.preventDefault();if(!busy)onClose()}}><header><span className="eyebrow">ACOMPANHAMENTO</span><button aria-label="Fechar acompanhamento" disabled={busy} onClick={onClose}><X size={18}/></button></header><h2>{plan.title}</h2><p className="plan-description">{plan.description||'Sem descrição.'}</p><div className="plan-meta"><span>Prioridade {priorities[plan.priority].toLowerCase()}</span><span>{dateText(plan.due_on)}</span><button disabled={busy} onClick={onEdit}>Editar plano</button></div><p className="daily-note">O prazo indica atraso; a mudança de etapa é feita por você.</p><label>Andamento<select value={plan.status} disabled={busy} onChange={e=>onStatus(e.target.value)}>{Object.entries(stages).map(([v,t])=><option value={v} key={v}>{t}</option>)}</select></label>{error&&<p role="alert" className="workspace-error">{error}</p>}<form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const message=String(new FormData(form).get('message'));if(await onNote(message))form.reset()}}><label>Registrar atualização<textarea name="message" required maxLength={4000} rows={3} placeholder="O que foi feito? Qual foi a resposta ou o resultado?"/></label><button className="primary-button" disabled={busy}>{busy?'Salvando…':'Adicionar ao histórico'}</button></form><h3>Histórico de acompanhamento</h3>{!history.length?<p>A primeira atualização começa o histórico deste plano.</p>:<ol className="timeline">{history.map(h=><li key={h.id}><time>{new Date(h.created_at).toLocaleString('pt-BR')}</time><p>{h.message}</p></li>)}</ol>}</dialog>
}
