import {phoneMask,documentMask,maskedChange,maskedKeyDown} from './inputMasks';
import React,{useEffect,useRef,useState} from 'react';
import {Package,Users,Tags,BadgeDollarSign,Plus,Pencil,Search} from 'lucide-react';
import {money,Requester,Row} from './BusinessPages';
import './catalog.css';
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function CatalogPage({base,request,customers=false}:{base:string;request:Requester;customers?:boolean}){
 const [compact,setCompact]=useState(()=>window.matchMedia('(max-width: 1200px)').matches);
 useEffect(()=>{const media=window.matchMedia('(max-width: 1200px)');const update=()=>setCompact(media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
 const modal=customers||compact;
 const table=customers?'customers':'products',singular=customers?'cliente':'produto';
 const [rows,setRows]=useState<Row[]>([]),[logs,setLogs]=useState<Row[]>([]),[selected,setSelected]=useState(''),[edit,setEdit]=useState<Row|null>(null),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[version,setVersion]=useState(0);
 const dialog=useRef<HTMLDialogElement>(null),formRef=useRef<HTMLFormElement>(null);
 useEffect(()=>{let alive=true;setLoading(true);Promise.all([request(base+'/records/'+table).then(r=>r.json()),customers?request(base+'/records/customer_contacts').then(r=>r.json()):Promise.resolve([])]).then(([r,l])=>{if(alive){setRows(r);setLogs(l);setSelected(old=>r.some((x:Row)=>x.id===old)?old:r[0]?.id||'')}}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[base,table,version]);
 async function save(path:string,values:Row,method='POST'){setBusy(true);setError('');setNotice('');try{const r=await (await request(base+'/records/'+path,{method,body:JSON.stringify(values)})).json();setVersion(v=>v+1);setNotice('Dados salvos com sucesso.');return r}catch(e){setError((e as Error).message);return null}finally{setBusy(false)}}
 function open(record:Row|null=null){setEdit(record);setError('');if(modal)dialog.current?.showModal();else setTimeout(()=>{formRef.current?.scrollIntoView({behavior:'smooth',block:'nearest'});formRef.current?.querySelector('input')?.focus()},0)}
 const categories=[...new Set(rows.map(r=>r.category).filter(Boolean))].sort();
 const visible=rows.filter(r=>(!category||r.category===category)&&normalize([r.name,r.sku,r.category,r.phone,r.email,r.document].join(' ')).includes(normalize(query))||customers&&query.replace(/\D/g,'').length>=3&&[r.phone,r.document].some(v=>String(v||'').replace(/\D/g,'').includes(query.replace(/\D/g,'')))).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));
 const current=rows.find(r=>r.id===selected),history=logs.filter(r=>r.customer_id===selected).sort((a,b)=>b.created_at.localeCompare(a.created_at));
 const fields=customers?[['name','Nome do cliente','Nome completo',160],['phone','Telefone','(00) 00000-0000',40],['document','CPF/CNPJ','CPF ou CNPJ',30],['email','E-mail','nome@empresa.com.br',254],['pix_key','Chave PIX','CPF, e-mail, telefone ou chave aleatória',254],['address','Endereço','Rua, número e complemento',300],['city','Cidade','Cidade / UF',120]]:[['name','Produto','Ex.: Caneca de cerâmica',120],['sku','SKU','Código único do produto',80],['category','Categoria','Ex.: Casa e decoração',80]];
 const editor=<form ref={formRef} key={edit?.id||'new'} className="catalog-form" onSubmit={async e=>{e.preventDefault();const values:Row=Object.fromEntries(new FormData(e.currentTarget));if(!customers){values.unit_cost=Math.round(Number(values.unit_cost)*100);values.unit_price=Math.round(Number(values.unit_price)*100);values.active=values.active==='on'}const result=await save(table+(edit?'/'+edit.id:''),values,edit?'PATCH':'POST');if(result){if(customers)setSelected(result.id);if(modal)dialog.current?.close();setEdit(null);formRef.current?.reset()}}}>
 <div className="catalog-form-heading"><span className="eyebrow">{edit?'EDITAR CADASTRO':'NOVO CADASTRO'}</span><h2 id="catalog-editor-title">{edit?'Editar':'Adicionar'} {singular}</h2><p>{customers?'Informações de contato e detalhes para um atendimento próximo.':'Organize seu catálogo com custos e preços sempre à mão.'}</p></div>
 <div className="catalog-fields">{fields.map(([key,label,placeholder,max])=><label key={key} className={key==='name'||key==='pix_key'?'wide':''}>{label}<input name={String(key)} placeholder={String(placeholder)} defaultValue={key==='phone'?phoneMask(edit?.phone||''):key==='document'?documentMask(edit?.document||''):edit?.[key]||''} onChange={key==='phone'?maskedChange(phoneMask):key==='document'?maskedChange(documentMask):undefined} onKeyDown={key==='phone'?maskedKeyDown(phoneMask):key==='document'?maskedKeyDown(documentMask):undefined} required={key==='name'||!customers} minLength={customers&&key==='name'?2:1} maxLength={Number(max)} type={key==='email'?'email':key==='phone'?'tel':'text'} list={key==='category'?'catalog-categories':undefined}/></label>)}{!customers&&<><datalist id="catalog-categories">{categories.map(c=><option key={c} value={c}/>)}</datalist><label>Custo unitário (R$)<input name="unit_cost" type="number" step="0.01" min="0" max="10000000000" required defaultValue={edit?edit.unit_cost/100:''} placeholder="0,00"/></label><label>Preço unitário (R$)<input name="unit_price" type="number" step="0.01" min="0.01" max="10000000000" required defaultValue={edit?edit.unit_price/100:''} placeholder="0,00"/></label></>}<label className="wide">Observações<textarea name="notes" rows={3} maxLength={4000} defaultValue={edit?.notes||''} placeholder={customers?'Preferências e informações úteis sobre o cliente':'Detalhes, especificações ou orientações sobre o produto'}/></label>{!customers&&<label className="catalog-check wide"><input type="checkbox" name="active" defaultChecked={edit?.active??true}/> Produto ativo</label>}</div>
 {error&&modal&&<p role="alert" className="workspace-error">{error}</p>}<div className="catalog-form-actions"><button type="button" disabled={busy} className="catalog-secondary" onClick={()=>{setEdit(null);formRef.current?.reset();if(modal)dialog.current?.close()}}>{modal||edit?'Cancelar':'Limpar'}</button><button disabled={busy} type="submit">{busy?'Salvando…':edit?'Salvar alterações':'Salvar '+singular}</button></div></form>;
 return <section className="catalog-page"><div className="catalog-toolbar"><div><span className="eyebrow">{customers?'RELACIONAMENTO':'CATÁLOGO DA EMPRESA'}</span><h2>{customers?'Conheça quem compra de você.':'Seu catálogo, bem cuidado.'}</h2><p>{customers?'Cadastros, observações e conversas em um só lugar.':'Produtos organizados para decisões melhores no dia a dia.'}</p></div><button onClick={()=>open()}><Plus size={17}/>{customers?'Cadastrar cliente':'Adicionar produto'}</button></div>
 <div className="catalog-metrics">{(customers?[[Users,'Clientes cadastrados',rows.length],[Users,'Com contato informado',rows.filter(r=>r.phone||r.email).length],[Tags,'Cidades atendidas',new Set(rows.map(r=>r.city).filter(Boolean)).size],[BadgeDollarSign,'Atendimentos registrados',logs.length]]:[[Package,'Produtos cadastrados',rows.length],[Package,'Produtos ativos',rows.filter(r=>r.active).length],[Tags,'Categorias',categories.length],[BadgeDollarSign,'Preço médio de venda',money(rows.length?Math.round(rows.reduce((n,r)=>n+r.unit_price,0)/rows.length):0)]]).map(([Icon,label,value])=>{const Glyph=Icon as typeof Package;return <article key={String(label)}><span className="catalog-icon"><Glyph size={21}/></span><div><strong>{String(value)}</strong><span>{String(label)}</span></div></article>})}</div>
 {error&&!dialog.current?.open&&<p role="alert" className="workspace-error">{error}</p>}{notice&&<p role="status" className="workspace-notice">{notice}</p>}{loading&&<p role="status">Carregando cadastros…</p>}
 <div className={'catalog-layout '+(customers?'catalog-customers':'')}>{!modal&&<aside className="catalog-card">{editor}</aside>}<article className="catalog-card catalog-list"><header><h2>{customers?'Lista de clientes':'Lista de produtos'}</h2><span>{visible.length} de {rows.length}</span></header><div className="catalog-filters"><label className="catalog-search"><Search size={17}/><input aria-label={customers?'Buscar cliente':'Buscar produto'} value={query} placeholder={customers?'Buscar por nome, documento ou contato…':'Buscar por nome, SKU ou categoria…'} onChange={e=>setQuery(e.target.value)}/></label>{!customers&&<select aria-label="Filtrar categoria" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas as categorias</option>{categories.map(c=><option key={c}>{c}</option>)}</select>}</div><div className="workspace-table" tabIndex={0} role="region" aria-label={customers?'Lista de clientes cadastrados':'Lista de produtos cadastrados'}><table><thead><tr>{(customers?['Cliente','Telefone / e-mail','Cidade','Ações']:['Produto','SKU','Categoria','Custo','Preço de venda','Status','Ações']).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><strong>{r.name}</strong></td>{customers?<><td>{phoneMask(r.phone||'')||r.email||'Não informado'}</td><td>{r.city||'—'}</td></>:<><td>{r.sku}</td><td><span className="catalog-tag">{r.category}</span></td><td>{money(r.unit_cost)}</td><td><strong>{money(r.unit_price)}</strong></td><td>{r.active?'Ativo':'Inativo'}</td></>}<td><div className="catalog-row-actions">{customers&&<button className="catalog-secondary" onClick={()=>setSelected(r.id)}>Ver perfil</button>}<button className="catalog-secondary" aria-label={'Editar '+r.name} onClick={()=>open(r)}><Pencil size={15}/></button></div></td></tr>)}</tbody></table></div>{!loading&&!visible.length&&<div className="empty-state"><Package size={30}/><h3>{rows.length?'Nenhum resultado para esta busca':'Seu primeiro '+singular+' começa aqui'}</h3><p>{rows.length?'Tente outro nome ou ajuste os filtros.':'Use o formulário para começar seu cadastro.'}</p></div>}</article></div>
 {modal&&<dialog ref={dialog} className="catalog-dialog" aria-labelledby="catalog-editor-title" onCancel={e=>{if(busy)e.preventDefault()}}>{editor}</dialog>}{customers&&<>{current&&<article className="catalog-card customer-profile"><header><div><span className="eyebrow">PERFIL DO CLIENTE</span><h2>{current.name}</h2></div><button className="catalog-secondary" onClick={()=>open(current)}>Editar cadastro</button></header><dl className="customer-details">{[['Telefone',phoneMask(current.phone||'')],['E-mail',current.email],['CPF/CNPJ',documentMask(current.document||'')],['Chave PIX',current.pix_key],['Endereço',current.address],['Cidade',current.city],['Observações',current.notes]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Não informado'}</dd></div>)}</dl><div className="customer-history"><form className="catalog-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const values:Row=Object.fromEntries(new FormData(form));values.customer_id=selected;values.next_on=values.next_on||null;if(await save('customer_contacts',values))form.reset()}}><h3>Registrar atendimento</h3><label>Canal<select name="channel"><option value="whatsapp">WhatsApp</option><option value="phone">Telefone</option><option value="email">E-mail</option><option value="store">Loja</option><option value="other">Outro</option></select></label><label>Contato realizado<textarea name="message" required maxLength={4000}/></label><label>Resposta do cliente<textarea name="response" maxLength={4000}/></label><label>Próximo retorno<input name="next_on" type="date"/></label><button disabled={busy}>Registrar no histórico</button></form><div><h3>Histórico de atendimentos</h3>{!history.length&&<p>Nenhum atendimento registrado para este cliente.</p>}<ol className="timeline">{history.map(r=><li key={r.id}><small>{new Date(r.created_at).toLocaleString('pt-BR')} · {({whatsapp:'WhatsApp',phone:'Telefone',email:'E-mail',store:'Loja',other:'Outro'} as Row)[r.channel]}</small><p>{r.message}</p>{r.response&&<blockquote>{r.response}</blockquote>}{r.next_on&&<small>Retornar em {r.next_on.split('-').reverse().join('/')}</small>}</li>)}</ol></div></div></article>}</>}
 </section>
}
