import React,{useEffect,useState} from 'react';
import {Upload,FileSpreadsheet,CheckCircle2,ArrowRight,ShieldCheck} from 'lucide-react';
import {labels,Requester,Row} from './BusinessPages';
import './imports.css';
export function ImportCenter({base,request}:{base:string;request:Requester}){
 const [step,setStep]=useState(1),[kind,setKind]=useState('products'),[file,setFile]=useState<Row|null>(null),[meta,setMeta]=useState<Row|null>(null),[mapping,setMapping]=useState<Record<string,string>>({}),[sheet,setSheet]=useState(''),[preview,setPreview]=useState<Row|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[uploadKey,setUploadKey]=useState(0);
 const [integration,setIntegration]=useState<Row>({sources:[],mappings:[]}),[source,setSource]=useState(''),[profileName,setProfileName]=useState(''),[activeProfile,setActiveProfile]=useState('');
 async function loadProfiles(){setIntegration(await (await request(base+'/integrations')).json())}
 useEffect(()=>{let alive=true;request(base+'/integrations').then(r=>r.json()).then(r=>{if(alive)setIntegration(r)}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[base]);
 async function run(work:()=>Promise<void>){setBusy(true);setError('');try{await work()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function read(f:Row,selected=''){setPreview(null);setActiveProfile('');const data=await (await request(base+'/spreadsheets/read',{method:'POST',body:JSON.stringify({...f,kind,sheet:selected||null})})).json();setMeta(data);setSheet(selected||data.sheets[0]||'');const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');setMapping(Object.fromEntries(data.fields.map((f:Row)=>[f.key,data.headers.find((h:string)=>normalize(h)===normalize(f.key)||normalize(h)===normalize(labels[f.key]||''))||''])));setStep(2)}
 const payload={...file,kind,source_id:source||null,sheet:sheet||null,mapping:Object.fromEntries(Object.entries(mapping).filter(([,v])=>v))};
 const missing=meta?.fields.filter((f:Row)=>f.required&&!mapping[f.key])||[];
 function reset(){setFile(null);setMeta(null);setPreview(null);setMapping({});setActiveProfile('');setStep(1);setUploadKey(k=>k+1)}
 const names:Row={products:'Produtos',sales:'Vendas',expenses:'Despesas'};
 return <section className="import-wizard" aria-busy={busy}><div className="import-hero"><span className="import-symbol"><Upload size={24}/></span><div><span className="eyebrow">SEUS DADOS, ORGANIZADOS</span><h2>Da planilha para a gestão.</h2><p>Confira cada etapa. Os registros só entram na empresa depois da sua confirmação.</p></div><a href="#/workspace/integrations">Ver histórico de importações →</a></div>
 <ol className="import-progress" aria-label="Etapas da importação">{['Escolher arquivo','Relacionar colunas','Conferir e importar'].map((label,i)=><li key={label} className={step===i+1?'current':step>i+1?'completed':''} aria-current={step===i+1?'step':undefined}><span>{step>i+1?<CheckCircle2 size={18}/>:String(i+1).padStart(2,'0')}</span><div><strong>{label}</strong><small>{['CSV ou Excel','Diga onde está cada informação','Valide antes de salvar'][i]}</small></div></li>)}</ol>
 {error&&<p role="alert" className="workspace-error">{error}</p>}{notice&&<p role="status" className="workspace-notice">{notice}</p>}{busy&&<p role="status">Processando arquivo…</p>}
 {file&&step>1&&<div className="import-file-summary"><FileSpreadsheet size={22}/><div><strong>{file.filename}</strong><small>{names[kind]} · {meta?.count||0} linhas encontradas</small></div><button disabled={busy} onClick={()=>{setStep(1);setPreview(null)}}>Trocar arquivo</button></div>}
 {step===1&&<div className="import-start-grid"><article className="workspace-content"><span className="eyebrow">PASSO 01</span><h2>Escolha o que vai importar</h2><label>O que deseja importar?<select value={kind} disabled={busy} onChange={e=>{setKind(e.target.value);reset();setNotice('')}}><option value="products">Produtos</option><option value="sales">Vendas</option><option value="expenses">Despesas</option></select></label><label className="import-upload"><FileSpreadsheet size={32}/><strong>Escolha a planilha</strong><span>CSV ou Excel (.xlsx) · até 2 MB</span><input key={kind+uploadKey} type="file" accept=".csv,.xlsx" disabled={busy} aria-label="Escolha a planilha" onChange={e=>{const f=e.target.files?.[0];if(!f)return;setNotice('');setMeta(null);setPreview(null);setFile(null);run(async()=>{if(f.size>2000000)throw Error('O arquivo deve ter no máximo 2 MB.');const bytes=new Uint8Array(await f.arrayBuffer());let binary='';bytes.forEach(b=>binary+=String.fromCharCode(b));const data={filename:f.name,content:btoa(binary)};setFile(data);await read(data)})}}/></label><details className="import-advanced"><summary>Origem e integrações (opcional)</summary><p>Use uma origem cadastrada para acompanhar arquivos de um ERP e reutilizar as relações de colunas.</p><label>Origem dos dados<select disabled={busy} value={source} onChange={e=>{setSource(e.target.value);setActiveProfile('');setPreview(null)}}><option value="">Arquivo avulso</option>{integration.sources.map((s:Row)=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><a href="#/workspace/integrations">Gerenciar origens →</a></details>{meta&&<button disabled={busy} onClick={()=>setStep(2)}>Continuar com este arquivo <ArrowRight size={16}/></button>}</article><aside className="import-guide"><ShieldCheck size={25}/><h2>Antes de começar</h2><ul><li>A primeira linha deve conter o nome das colunas.</li><li>O arquivo pode ter até 1.000 registros.</li><li>Informe valores em reais e datas como DD/MM/AAAA ou AAAA-MM-DD.</li><li>Converta fórmulas em valores antes de enviar.</li></ul><div><strong>Importação segura</strong><p>Erros ou identificadores repetidos impedem a importação de todo o lote. Você poderá revisar antes de confirmar.</p></div><a href="#/workspace/bank_imports">Importar recebimentos de extrato →</a></aside></div>}
 {step===2&&meta&&<article className="workspace-content import-mapping"><div className="import-section-title"><div><span className="eyebrow">PASSO 02</span><h2>Onde está cada informação?</h2><p>À esquerda, o campo do Lucra. À direita, escolha a coluna correspondente do arquivo.</p></div><span className="import-count">{missing.length?missing.length+' obrigatórios pendentes':'Obrigatórios relacionados'}</span></div>{meta.sheets.length>1&&<label>Aba da planilha<select value={sheet} disabled={busy} onChange={e=>run(()=>read(file!,e.target.value))}>{meta.sheets.map((s:string)=><option key={s}>{s}</option>)}</select></label>}
 {!!integration.mappings.filter((m:Row)=>m.kind===kind&&m.source_id===source).length&&<label>Reutilizar mapeamento<select value={activeProfile} disabled={busy} onChange={e=>{setActiveProfile(e.target.value);const profile=integration.mappings.find((m:Row)=>m.id===e.target.value);if(profile){setMapping(Object.fromEntries(Object.entries(profile.mapping).filter(([,v])=>meta.headers.includes(v))) as Record<string,string>);setPreview(null)}}}><option value="">Escolha um mapeamento salvo</option>{integration.mappings.filter((m:Row)=>m.kind===kind&&m.source_id===source).map((m:Row)=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>}
 <div className="import-column-grid">{meta.fields.map((f:Row)=><label className="import-column" key={f.key}><span><strong>{labels[f.key]||f.key}</strong><small>{f.required?'Obrigatório':'Opcional'}</small></span><select aria-label={(labels[f.key]||f.key)+(f.required?' *':'')} disabled={busy} value={mapping[f.key]||''} onChange={e=>{setMapping({...mapping,[f.key]:e.target.value});setActiveProfile('');setPreview(null)}}><option value="">{f.required?'Selecione uma coluna':'Usar padrão'}</option>{meta.headers.map((h:string)=><option key={h}>{h}</option>)}</select></label>)}</div>
 <details><summary>Ver amostra do arquivo · primeiras 5 linhas</summary><div className="workspace-table" tabIndex={0} role="region" aria-label="Amostra do arquivo"><table><thead><tr>{meta.headers.map((h:string)=><th key={h}>{h}</th>)}</tr></thead><tbody>{meta.sample.map((r:Row,i:number)=><tr key={i}>{meta.headers.map((h:string)=><td key={h}>{String(r[h]??'')}</td>)}</tr>)}</tbody></table></div></details>{source&&<details><summary>Salvar relação de colunas para reutilizar</summary><div className="mapping-save"><label>Nome do mapeamento<input value={profileName} maxLength={100} placeholder="Ex.: Exportação mensal" onChange={e=>setProfileName(e.target.value)}/></label><button disabled={busy||profileName.trim().length<2||missing.length>0} onClick={()=>run(async()=>{await request(base+'/integrations/mappings',{method:'POST',body:JSON.stringify({source_id:source,kind,name:profileName,mapping:payload.mapping})});await loadProfiles();setProfileName('');setNotice('Mapeamento salvo para esta empresa e origem.')})}>Salvar mapeamento</button></div></details>}
 <div className="import-actions"><button disabled={busy} onClick={()=>setStep(1)}>Voltar</button><button disabled={busy||missing.length>0} className="primary-button" onClick={()=>run(async()=>{const result=await (await request(base+'/spreadsheets/preview',{method:'POST',body:JSON.stringify(payload)})).json();setPreview(result);setStep(3)})}>Validar e visualizar <ArrowRight size={16}/></button></div></article>}
 {step===3&&preview&&meta&&<article className="workspace-content import-confirm"><span className="eyebrow">PASSO 03</span><h2>{preview.can_import?'Tudo pronto para sua conferência':'Revise os pontos encontrados'}</h2><div className="import-validation"><div><strong>{preview.rows.length}</strong><span>Registros válidos</span></div><div><strong>{preview.errors.length}</strong><span>Erros encontrados</span></div><div><strong>{preview.duplicates.length}</strong><span>Identificadores repetidos</span></div></div>{preview.errors.map((e:Row)=><p role="alert" className="workspace-error" key={e.line}>Linha {e.line}: {e.message}</p>)}{!!preview.duplicates.length&&<p role="alert" className="workspace-error">Já cadastrados: {preview.duplicates.join(', ')}</p>}<h3>Prévia dos registros convertidos</h3><p>Até 20 linhas para conferência. Valores monetários abaixo estão em reais.</p><div className="workspace-table" tabIndex={0} role="region" aria-label="Prévia da importação"><table><thead><tr>{meta.fields.map((f:Row)=><th key={f.key}>{labels[f.key]||f.key}</th>)}</tr></thead><tbody>{preview.rows.slice(0,20).map((r:Row,i:number)=><tr key={i}>{meta.fields.map((f:Row)=><td key={f.key}>{['unit_cost','unit_price','revenue','cmv','tax','card','commission','amount'].includes(f.key)&&r[f.key]!=null?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(r[f.key])/100):typeof r[f.key]==='boolean'?(r[f.key]?'Sim':'Não'):String(r[f.key]??'—')}</td>)}</tr>)}</tbody></table></div><p className="import-safety"><ShieldCheck size={18}/> Os registros serão adicionados à empresa ativa. Nada foi gravado até aqui.</p><div className="import-actions"><button disabled={busy} onClick={()=>setStep(2)}>Revisar colunas</button><button className="primary-button" disabled={busy||!preview.can_import} onClick={()=>run(async()=>{const result=await (await request(base+'/spreadsheets/confirm',{method:'POST',body:JSON.stringify(payload)})).json();reset();setNotice(`${result.imported} registros importados com sucesso.`)})}>Confirmar importação</button></div></article>}
 </section>
}
