import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDown, ArrowDownToLine, ArrowRight, ArrowUpRight, BarChart3, Bell, CalendarDays, Check, CheckCheck, ChevronDown, ChevronRight, CircleHelp, CreditCard, FileText, LayoutDashboard, LoaderCircle, Package, Search, Settings2, ShieldCheck, Sparkles, TrendingUp, TriangleAlert, Wallet, X } from 'lucide-react';
import './styles.css';
import {Workspace, DynamicWaterfall} from './Workspace';

const money = (n: number) => new Intl.NumberFormat('pt-BR', {style:'currency',currency:'BRL', maximumFractionDigits:2}).format(n/100);
const percent = (n:number) => n.toLocaleString('pt-BR',{maximumFractionDigits:1})+'%';
type Period = 'daily'|'weekly'|'monthly';
type Product = {name:string;category:string;quantity:number;installments:number;revenue:number;net:number;margin:number};
type Dashboard = {start:string;end:string;totals:Record<string,number>;products:Product[];daily:{date:string;estimated:number;net:number}[]};
const labels = {daily:'Diário',weekly:'Semanal',monthly:'Mensal'};
const dateText = (s:string) => new Date(s+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'}).replace('.','');

function App(){
 const [period,setPeriod] = useState<Period>('monthly');
 const [anchor,setAnchor] = useState('2026-08-31');
 const [data,setData] = useState<Dashboard|null>(null);
 const [loading,setLoading] = useState(true);
 const [error,setError] = useState('');
 const [retry,setRetry] = useState(0);
 const [page,setPage] = useState(location.hash.split('/')[2]||'overview');
 useEffect(()=>{const sync=()=>setPage(location.hash.split('/')[2]||'overview');window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);
 const [query,setQuery] = useState('');
 const [downloading,setDownloading] = useState(false);
 const [toast,setToast] = useState('');
 const [help,setHelp] = useState(false);
 const [alerts,setAlerts] = useState(false);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetch(`/api/dashboard?period=${period}&anchor=${anchor}`,{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setData).catch(e=>{if(e.name!=='AbortError')setError('Não foi possível carregar os dados. Verifique se a API está em execução.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[period,anchor,retry]);
 useEffect(()=>{if(toast){const id=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(id)}},[toast]);
 async function download(){setDownloading(true);try{const r=await fetch(`/api/reports/pdf?period=${period}&anchor=${anchor}`);if(!r.ok)throw Error();const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`lucra-${period}-${anchor}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setToast('Seu relatório está pronto. Download iniciado.')}catch{setToast('Não foi possível gerar o PDF. Tente novamente.')}finally{setDownloading(false)}}
 const negative=data?.products.filter(p=>p.net<0)||[];
 const t=data?.totals;
 const navigate=(next:string)=>{location.hash='/demo/'+next;setPage(next);setQuery('');window.scrollTo({top:0,behavior:'smooth'})};
 return <div className="app-shell">
  <aside className="sidebar">
   <a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('overview')}}><span className="brand-symbol"><BarChart3 size={24}/></span>lucra<span className="brand-dot">.</span></a>
   <div className="workspace"><span className="store-avatar">CN</span><div><b>Casa Nova Store</b><small>Seu negócio, mais claro</small></div><ChevronDown size={15}/></div>
   <div className="nav-label">WORKSPACE</div>
   <nav>{[{id:'overview',icon:LayoutDashboard,label:'Visão geral'},{id:'products',icon:Package,label:'Produtos e margens'},{id:'simulator',icon:CreditCard,label:'Simulador de preço'},{id:'reports',icon:FileText,label:'Relatórios'}].map(n=><button key={n.id} onClick={()=>navigate(n.id)} className={page===n.id?'nav-item active':'nav-item'}><n.icon size={19}/>{n.label}{page===n.id&&<span className="active-dot"/>}</button>)}</nav>
   <div className="sidebar-bottom"><div className="insight-box"><span className="insight-icon"><Sparkles size={18}/></span><b>Vender mais é bom.<br/>Lucrar melhor é essencial.</b><p>Transforme seus números em decisões mais inteligentes.</p><button onClick={()=>setHelp(true)}>Entenda seus indicadores <ArrowUpRight size={15}/></button></div><button className="help-button" onClick={()=>setHelp(true)}><CircleHelp size={18}/> Central de ajuda <ArrowUpRight size={15}/></button><div className="user"><span className="user-avatar">MA</span><div><b>Matheus & equipe</b><small>Administradores</small></div><span className="online-dot"/></div></div>
  </aside>
  <div className="main-shell">
   <header className="topbar"><div className="breadcrumb">Workspace <ChevronRight size={14}/><b>{{overview:'Visão geral',products:'Produtos e margens',simulator:'Simulador de preço',reports:'Relatórios'}[page]}</b></div><div className="top-actions"><a className="primary-button" href="#/workspace/dashboard">Entrar na minha empresa</a><span className="demo-badge"><span/> Ambiente de demonstração</span><button className="icon-button notification" aria-label="Ver alertas" onClick={()=>setAlerts(!alerts)}><Bell size={19}/><i/></button><span className="mini-avatar">MA</span></div></header>
   {alerts&&<div className="notification-panel"><b>Alertas do período</b><button aria-label="Fechar alertas" onClick={()=>setAlerts(false)}><X size={16}/></button><p>{negative.length} produtos têm margem negativa.</p><button className="text-link" onClick={()=>{navigate('products');setAlerts(false)}}>Revisar produtos <ArrowRight size={14}/></button></div>}
   <main>
    <div className="heading-row"><div><div className="eyebrow">CLAREZA PARA DECIDIR MELHOR</div><h1>{{overview:'Seu negócio, sem pontos cegos.',products:'Cada produto conta.',simulator:'O preço certo começa aqui.',reports:'Seus resultados, organizados.'}[page]}</h1><p className="subtitle">{{overview:'Descubra o que você vende, o que você ganha e o que fica pelo caminho.',products:'Encontre o que vende bem, mas deixa dinheiro pelo caminho.',simulator:'Veja o impacto das taxas antes de fechar a próxima venda.',reports:'Uma visão clara da empresa, pronta para compartilhar.'}[page]}</p></div><button className="primary-button" onClick={download} disabled={downloading||loading||!!error}>{downloading?<LoaderCircle size={16} className="spin"/>:<ArrowDownToLine size={16}/>} {downloading?'Gerando PDF…':'Exportar relatório'}</button></div>
    <div className="toolbar"><div className="period-tabs" aria-label="Período">{(Object.keys(labels) as Period[]).map(p=><button aria-pressed={p===period} key={p} className={p===period?'selected':''} onClick={()=>setPeriod(p)}>{labels[p]}</button>)}</div><label className="date-picker"><CalendarDays size={16}/><input aria-label="Data de referência" type="date" value={anchor} onChange={e=>{if(e.target.value)setAnchor(e.target.value)}}/></label><span className="data-status"><span/>{data&&!loading?`${dateText(data.start)} – ${dateText(data.end)} · Dados fictícios`:'Carregando informações'}</span></div>
    {error?<div className="empty-state"><TriangleAlert/><h2>Não conseguimos carregar o painel</h2><p>{error}</p><button className="primary-button" onClick={()=>setRetry(retry+1)}>Tentar novamente</button></div>:loading?<div className="loading-state"><LoaderCircle className="spin"/> Organizando seus números…</div>:data&&t&&<>
    {!t.quantity&&<div className="no-sales"><CalendarDays size={18}/> Nenhuma venda neste período. A demonstração contém dados de julho e agosto de 2026.<button onClick={()=>{setAnchor('2026-08-31');setPeriod('monthly')}}>Ver agosto</button></div>}
    {page==='overview'&&<>
     <div className="metrics-grid">
      <Metric label="Faturamento total" value={money(t.revenue)} icon={<Wallet size={18}/>} foot={<><span className="neutral-tag">{t.quantity} vendas</span><span>no período selecionado</span></>}/>
      <Metric label="Lucro estimado pelo dono" value={money(t.estimated)} icon={<TrendingUp size={18}/>} foot={<><span className="muted-dot"/> Receita menos custo de aquisição</>}/>
      <Metric label="Resultado real das vendas" value={money(t.net)} icon={<ShieldCheck size={18}/>} green foot={<><span className="green-tag">{percent(t.margin)} de margem</span><span>após deduções</span></>}/>
      <Metric label="Custos que passam despercebidos" value={money(t.hidden)} icon={<Search size={18}/>} foot={<><span className="red-tag">{percent(t.estimated?t.hidden/t.estimated*100:0)} do estimado</span><span>em deduções</span></>}/>
     </div>
     <div className="alert-strip"><span className="alert-icon"><TriangleAlert size={19}/></span><div><b>{negative.length?`Vender muito nem sempre significa lucrar.`:'Seus números estão organizados.'}</b><span>{negative.length?<> {negative.length} produtos estão sendo vendidos com margem negativa. Hora de rever as condições.</>:' Nenhum produto com margem negativa neste período.'}</span></div><button onClick={()=>navigate('products')}>Ver produtos <ArrowRight size={15}/></button></div>
     <div className="main-grid"><section className="panel profit-panel"><PanelTitle title="Lucro ilusório vs. lucro real" subtitle="A diferença entre o que parece e o que sobra." badge="ANÁLISE DO PERÍODO"/><div className="profit-comparison"><div><span>Na sua estimativa</span><strong>{money(t.estimated)}</strong></div><span className="comparison-arrow"><ArrowRight size={23}/></span><div className="real-profit"><span>Depois das deduções</span><strong>{money(t.net)}</strong></div><div className="gap-label"><ArrowDown size={14}/>{percent(t.estimated?t.hidden/t.estimated*100:0)}<small>de diferença</small></div></div><ProfitChart daily={data.daily}/><div className="chart-legend"><span><i className="legend-estimated"/>Lucro estimado</span><span><i className="legend-real"/>Resultado real</span></div><div className="deduction-timeline">{[{label:'Impostos',value:t.tax},{label:'Cartão + antecipação',value:t.card},{label:'Comissões',value:t.commission}].map((x,i)=><div key={x.label}><span className="timeline-point">{i+1}</span><span>{x.label}<b>− {money(x.value)}</b></span></div>)}</div></section>
      <section className="panel waterfall-panel"><PanelTitle title="Da receita ao resultado" subtitle="O caminho do faturamento até o resultado."/><DynamicWaterfall totals={t}/><div className="waterfall-caption"><span><Sparkles size={17}/></span><p>Faturamento não é lucro.<br/><b>Neste exemplo, só R$ 8 ficam com você.</b></p></div><small className="example-label">Exemplo didático · independente do período</small></section></div>
     <div className="bottom-grid"><ProductTable products={negative} compact query={query} setQuery={setQuery} onAll={()=>navigate('products')}/><Simulator compact/></div>
    </>}
    {page==='products'&&<ProductTable products={data.products} query={query} setQuery={setQuery}/>}
    {page==='simulator'&&<div className="standalone-simulator"><Simulator/><section className="panel methodology"><ShieldCheck size={30}/><h2>Decida com os custos à vista.</h2><p>Informe o CMV e ajuste as taxas ao contrato da sua empresa. O simulador considera imposto, comissão, taxa do cartão e antecipação.</p><h3>Como a antecipação é estimada?</h3><p>Taxa mensal × prazo médio das parcelas: (número de parcelas + 1) ÷ 2. O recebimento da primeira parcela é considerado em 30 dias.</p><p>Este é um modelo linear ilustrativo. Despesas fixas e regras específicas da operadora não estão incluídas.</p></section></div>}
    {page==='reports'&&<section className="panel report-page"><div className="report-icon"><FileText size={32}/></div><span className="eyebrow">DA ANÁLISE À AÇÃO</span><h2>O retrato do seu negócio em um PDF.</h2><p>Relatório {labels[period].toLowerCase()} de {dateText(data.start)} a {dateText(data.end)}.<br/>Receita, deduções, resultado e produtos no prejuízo, no mesmo documento.</p><div className="report-features"><span><Check size={17}/> Resumo financeiro</span><span><Check size={17}/> Produtos com margem negativa</span><span><Check size={17}/> Metodologia dos cálculos</span></div><button className="primary-button" disabled={downloading} onClick={download}><ArrowDownToLine size={17}/>{downloading?'Gerando…':'Baixar relatório em PDF'}</button><small>Use os filtros acima para escolher um dia, semana ou mês.</small></section>}
    <footer><span><ShieldCheck size={14}/> Dados demonstrativos · Casa Nova Store</span><span>Resultado antes de despesas fixas. Não representa saldo bancário. <button onClick={()=>setHelp(true)}>Saiba mais <ArrowUpRight size={12}/></button></span></footer>
    </>}
   </main>
  </div>
  {toast&&<div className="toast" role="status"><CheckCheck size={19}/>{toast}<button aria-label="Fechar aviso" onClick={()=>setToast('')}><X size={16}/></button></div>}
  {help&&<div className="modal-backdrop" onClick={()=>setHelp(false)}><section className="modal panel" role="dialog" aria-modal="true" aria-labelledby="help-title" onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" autoFocus aria-label="Fechar ajuda" onClick={()=>setHelp(false)}><X/></button><span className="eyebrow">ENTENDA SEUS NÚMEROS</span><h2 id="help-title">Mais clareza. Melhores decisões.</h2><p><b>Lucro estimado:</b> faturamento menos o custo das mercadorias (CMV).</p><p><b>Resultado real das vendas:</b> estimativa após impostos, cartão/antecipação e comissões. Ainda não desconta despesas fixas nem concilia o banco.</p><p><b>Itens no prejuízo:</b> produtos cuja soma das deduções supera a receita. A tabela é ordenada por unidades vendidas.</p><p><b>Dados demonstrativos:</b> empresa e transações fictícias de julho e agosto de 2026. Todas as taxas são premissas, incluindo o Simples Nacional.</p><button className="primary-button" onClick={()=>setHelp(false)}>Entendi <Check size={17}/></button></section></div>}
 </div>
}
function Metric({label,value,icon,foot,green=false}:{label:string;value:string;icon:React.ReactNode;foot:React.ReactNode;green?:boolean}){return <section className={`metric ${green?'metric-green':''}`}><div className="metric-label">{label}<span>{icon}</span></div><strong>{value}</strong><div className="metric-foot">{foot}</div></section>}
function PanelTitle({title,subtitle,badge}:{title:string;subtitle:string;badge?:string}){return <div className="panel-title"><div><h2>{title}</h2><p>{subtitle}</p></div>{badge&&<span className="small-badge">{badge}</span>}</div>}
function ProfitChart({daily}:{daily:Dashboard['daily']}){
 let e=0,n=0;const values=[{date:daily[0]?.date,estimated:0,net:0},...daily.map(d=>({date:d.date,estimated:e+=d.estimated,net:n+=d.net}))];
 const max=Math.max(...values.flatMap(d=>[d.estimated,d.net]),100);const min=Math.min(...values.map(d=>d.net),0);const ceiling=Math.ceil(max/1000000)*1000000;const y=(v:number)=>164-(v-min)/(ceiling-min)*144;const x=(i:number)=>48+i/(values.length-1||1)*532;
 const points=(key:'estimated'|'net')=>values.map((v,i)=>`${x(i)},${y(v[key])}`).join(' ');
 return <div className="profit-chart"><svg viewBox="0 0 600 196" role="img" aria-label="Evolução acumulada do lucro estimado e resultado real"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#80bda2" stopOpacity=".26"/><stop offset="100%" stopColor="#80bda2" stopOpacity=".01"/></linearGradient></defs>{[0,1,2,3].map(i=>{const value=min+(ceiling-min)*i/3;return <g key={i}><line x1="48" x2="580" y1={y(value)} y2={y(value)} stroke="#e9eeeb" strokeDasharray="3 5"/><text x="0" y={y(value)+4} fill="#929c97" fontSize="10">{Math.round(value/100000)} mil</text></g>})}<polygon points={`48,${y(0)} ${points('net')} 580,${y(0)}`} fill="url(#area)"/><polyline points={points('estimated')} fill="none" stroke="#b7c4bd" strokeWidth="2" strokeDasharray="5 5"/><polyline points={points('net')} fill="none" stroke="#267853" strokeWidth="3" strokeLinejoin="round"/>{[0,Math.floor(daily.length/2),daily.length-1].map((i,j)=><text key={j} x={48+(i+1)/(values.length-1)*532} y="189" textAnchor={j===2?'end':'middle'} fill="#8a948e" fontSize="10">{daily[i]?dateText(daily[i].date):''}</text>)}</svg></div>
}
function ProductTable({products,compact=false,query,setQuery,onAll}:{products:Product[];compact?:boolean;query:string;setQuery:(s:string)=>void;onAll?:()=>void}){const filtered=products.filter(p=>(p.name+' '+p.category).toLowerCase().includes(query.toLowerCase()));return <section className="panel products-panel"><div className="panel-title"><div><div className="title-with-count"><h2>{compact?'Itens no prejuízo':'Produtos e margens'}</h2><span className="count-badge">{products.length}</span></div><p>{compact?'Os mais vendidos que estão custando caro.':'Resultados por produto · ordenados por unidades vendidas'}</p></div>{compact?<span className="red-label"><span/> Atenção à margem</span>:<label className="search-field"><Search size={16}/><input placeholder="Buscar produto…" value={query} onChange={e=>setQuery(e.target.value)}/></label>}</div><div className="table-scroll"><table><thead><tr><th>Produto</th><th>Vendas <ArrowDown size={11}/></th><th>Parcelas</th><th>Margem</th><th>Resultado</th></tr></thead><tbody>{filtered.map((p,i)=><tr key={p.name+p.category+p.installments}><td><span className={`product-icon product-icon-${i%3}`}><Package size={18}/></span><div><b>{p.name}</b><small>{p.category}</small></div></td><td>{p.quantity}<small>unidades</small></td><td><span className="installment-tag">{p.installments}x</span></td><td><span className={p.net<0?'negative-margin':'positive-margin'}>{percent(p.margin)}</span></td><td className={p.net<0?'negative-value':'positive-value'}>{money(p.net)}</td></tr>)}</tbody></table>{!filtered.length&&<div className="table-empty">{query?'Nenhum produto encontrado.':'Nenhum item para exibir neste período.'}</div>}</div><div className="table-footer"><span><CircleHelp size={13}/> Margem após CMV, impostos, cartão e comissão</span>{compact&&<button onClick={onAll}>Ver todos <ArrowRight size={14}/></button>}</div></section>}
type SimResult={price:number;cost:number;tax:number;commission:number;card:number;net:number;margin:number;card_rate:number;breakeven:number|null};
function Simulator({compact=false}:{compact?:boolean}){
 const [price,setPrice]=useState('200');const [cost,setCost]=useState('140');const [installments,setInstallments]=useState('12');const [advanced,setAdvanced]=useState(false);
 const [tax,setTax]=useState('6');const [commission,setCommission]=useState('4');const [card,setCard]=useState('2');const [anticipation,setAnticipation]=useState('1.5');
 const [result,setResult]=useState<SimResult|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{setResult(null);setError('');const values=[price,cost,tax,commission,card,anticipation];if(values.some(v=>v===''||!Number.isFinite(Number(v)))||Number(price)<=0||values.slice(1).some(v=>Number(v)<0)){setError('Informe valores válidos. O preço deve ser maior que zero.');setBusy(false);return}const controller=new AbortController();setBusy(true);const timer=setTimeout(()=>{fetch('/api/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({price:Number(price),cost:Number(cost),installments:Number(installments),tax_rate:Number(tax),commission_rate:Number(commission),card_base:Number(card),anticipation_rate:Number(anticipation)}),signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setResult).catch(e=>{if(e.name!=='AbortError')setError('Confira os valores e a conexão com a API. Taxas: até 50%; antecipação: até 20%.')}).finally(()=>{if(!controller.signal.aborted)setBusy(false)})},250);return()=>{clearTimeout(timer);controller.abort()}},[price,cost,installments,tax,commission,card,anticipation]);
 return <section className={`panel simulator-panel ${compact?'compact':''}`}><PanelTitle title="Essa venda vale a pena?" subtitle="Simule o preço antes de dar o próximo desconto."/><div className="sim-inputs"><label>Preço de venda<div className="input-prefix"><span>R$</span><input aria-label="Preço de venda" type="number" min="0.01" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></div></label><label>Parcelamento<div className="select-wrap"><select aria-label="Parcelamento" value={installments} onChange={e=>setInstallments(e.target.value)}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{i+1}x {i===0?'no cartão':'sem juros'}</option>)}</select><ChevronDown size={14}/></div></label></div><div className="sim-cost-row"><label>Custo do produto (CMV)<div className="input-prefix"><span>R$</span><input aria-label="Custo do produto" type="number" min="0" step="0.01" value={cost} onChange={e=>setCost(e.target.value)}/></div></label><button className="settings-link" onClick={()=>setAdvanced(!advanced)}><Settings2 size={14}/>{advanced?'Ocultar taxas':'Ajustar taxas'}</button></div>{advanced&&<div className="advanced-fields">{[{label:'Imposto (%)',value:tax,set:setTax},{label:'Comissão (%)',value:commission,set:setCommission},{label:'Cartão / MDR (%)',value:card,set:setCard},{label:'Antecipação (% a.m.)',value:anticipation,set:setAnticipation}].map(f=><label key={f.label}>{f.label}<input type="number" min="0" step="0.1" value={f.value} onChange={e=>f.set(e.target.value)}/></label>)}</div>}<div aria-live="polite">{busy?<div className="sim-loading"><LoaderCircle size={17} className="spin"/> Calculando resultado…</div>:error?<div className="sim-error">{error}</div>:result&&<><div className={`simulation-result ${result.net<0?'loss':''}`}><span className="result-icon">{result.net<0?<TriangleAlert size={19}/>:<Check size={19}/>}</span><div><b>{result.net<0?'Essa venda dá prejuízo.':result.net===0?'Essa venda está no equilíbrio.':'Essa venda deixa margem.'}</b><span>Resultado por unidade</span></div><strong>{money(result.net)}<small>{percent(result.margin)} de margem</small></strong></div>{!compact&&<div className="sim-breakdown"><span>Impostos <b>{money(result.tax)}</b></span><span>Cartão + antecipação ({percent(result.card_rate)}) <b>{money(result.card)}</b></span><span>Comissão <b>{money(result.commission)}</b></span></div>}<p className="breakeven">{result.breakeven!==null?<>Preço de equilíbrio: <b>{money(result.breakeven)}</b></>:'As taxas consomem 100% ou mais do preço.'}</p></>}</div><div className="sim-note"><CircleHelp size={12}/> Taxas ilustrativas. Resultado antes das despesas fixas.</div></section>
}

function Root(){const [workspace,setWorkspace]=useState(!location.hash.startsWith('#/demo'));useEffect(()=>{const sync=()=>setWorkspace(!location.hash.startsWith('#/demo'));window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);return workspace?<Workspace/>:<App/>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><Root/></React.StrictMode>);
