import React,{useEffect,useRef,useState} from 'react';
import {Plus,Search,Wallet,Package,TrendingUp,CalendarDays} from 'lucide-react';
import {money,Requester,Row} from './BusinessPages';
import './operations.css';
type Field={key:string;label:string;type?:string;money?:boolean;options?:string[]};
const copy:Record<string,{title:string;action:string;save:string;hint:string}>={
 sales:{title:'Histórico de vendas',action:'Adicionar venda',save:'Salvar venda',hint:'Informe os totais da venda e os custos efetivamente cobrados. As taxas cadastradas não são aplicadas automaticamente.'},
 payables:{title:'Agenda de pagamentos',action:'Adicionar conta',save:'Salvar conta',hint:'O saldo considera os pagamentos registrados. Use Pagar conta para registrar uma baixa parcial ou total.'},
 bills:{title:'Contas cadastradas',action:'Adicionar conta',save:'Salvar conta',hint:'O cadastro da conta já registra a despesa na competência. Não lance o mesmo valor novamente em Despesas.'},
 bill_payments:{title:'Pagamentos registrados',action:'Registrar pagamento',save:'Salvar pagamento',hint:'Registre baixas parciais ou totais. Pagamentos superiores ao saldo da conta são bloqueados.'},
 inventory:{title:'Posição do estoque',action:'Movimentar estoque',save:'Salvar movimentação',hint:'Saldo das entradas e saídas registradas. As vendas não movimentam automaticamente o estoque.'},
 stock_movements:{title:'Histórico de movimentações',action:'Nova movimentação',save:'Salvar movimentação',hint:'Entradas aumentam o saldo; saídas reduzem. Para corrigir um movimento, registre o inverso com outra referência.'},
 payment_terms:{title:'Suas condições de pagamento',action:'Adicionar condição',save:'Salvar condição',hint:'Organize impostos, comissões e taxas por parcelamento. Selecione uma condição na nova venda ou no simulador para aplicar estas taxas. Vendas já lançadas preservam os valores históricos.'}
};
const labels:Record<string,string>={in:'Entrada',out:'Saída',paid:'Pago',overdue:'Vencido',pending:'Pendente'};
const norm=(v:unknown)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const dateLabel=(v:string)=>v?.split('-').reverse().join('/')||'—';
export function OperationsPage({area,base,request,fields}:{area:string;base:string;request:Requester;fields:Record<string,Field[]>}){
 const info=copy[area],table=area==='payables'?'bills':area==='inventory'?'stock_movements':area;
 const [rows,setRows]=useState<Row[]>([]),[linked,setLinked]=useState<Row[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[version,setVersion]=useState(0),[edit,setEdit]=useState<Row|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{let live=true;setLoading(true);const endpoint=['inventory','payables'].includes(area)?'/'+area:'/records/'+area;const relation=table==='stock_movements'?'products':table==='bill_payments'?'bills':null;
 Promise.all([request(base+endpoint).then(r=>r.json()),relation?request(base+'/records/'+relation).then(r=>r.json()):Promise.resolve([])]).then(([r,l])=>{if(live){setRows(r);setLinked(l)}}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[area,base,version]);
 const dateKey=area==='sales'?'sold_on':['payables','bills'].includes(area)?'due_on':area==='stock_movements'?'occurred_on':'paid_on';
 const dated=['sales','payables','bills','stock_movements','bill_payments'].includes(area);
 const display:Row[]=rows.map(r=>({...r,original_product_id:r.product_id,product_id:linked.find(x=>x.id===r.product_id)?.name||r.product_id,bill_id:linked.find(x=>x.id===r.bill_id)?.description||r.bill_id}));
 const visible=display.filter(r=>Object.values(r).some(v=>norm(v).includes(norm(query)))&&(!from||!dated||r[dateKey]>=from)&&(!to||!dated||r[dateKey]<=to)&&(!filter||(area==='inventory'?(filter==='empty'?r.balance<=0:r.balance>0):area==='payables'?r.status===filter:area==='stock_movements'?r.direction===filter:r.category===filter)));
 const sum=(key:string)=>visible.reduce((n,r)=>n+Number(r[key]||0),0);
 const metrics: [string,string|number][] = area==='sales'?[['Vendas exibidas',visible.length],['Receita',money(sum('revenue'))],['Custos e taxas',money(sum('cmv')+sum('tax')+sum('card')+sum('commission'))],['Resultado das vendas',money(sum('revenue')-sum('cmv')-sum('tax')-sum('card')-sum('commission'))]]:area==='payables'?[['Contas exibidas',visible.length],['Saldo a pagar',money(sum('balance'))],['Valor pago',money(sum('paid'))],['Saldo vencido',money(visible.filter(r=>r.status==='overdue').reduce((n,r)=>n+r.balance,0))]]:area==='inventory'?[['Produtos',visible.length],['Unidades em estoque',sum('balance')],['Sem saldo',visible.filter(r=>r.balance<=0).length],['Com saldo',visible.filter(r=>r.balance>0).length]]:area==='stock_movements'?[['Movimentações',visible.length],['Entradas (unidades)',visible.filter(r=>r.direction==='in').reduce((n,r)=>n+r.quantity,0)],['Saídas (unidades)',visible.filter(r=>r.direction==='out').reduce((n,r)=>n+r.quantity,0)],['Produtos movimentados',new Set(visible.map(r=>r.original_product_id)).size]]:area==='payment_terms'?[['Condições',visible.length],['À vista',visible.filter(r=>r.installments===1).length],['Parceladas',visible.filter(r=>r.installments>1).length],['Máximo de parcelas',Math.max(0,...visible.map(r=>r.installments))]]:[['Lançamentos',visible.length],['Valor registrado',money(sum('amount'))],['Referências',new Set(visible.map(r=>r.reference)).size],['Período',from||to?'Filtrado':'Todo o histórico']];
 const columns:string[][]=area==='inventory'?[['sku','SKU'],['name','Produto'],['balance','Saldo em unidades']]:area==='payables'?[['reference','Referência'],['supplier','Fornecedor'],['due_on','Vencimento'],['amount','Valor'],['paid','Pago'],['balance','Saldo'],['status','Situação']]:area==='sales'?[['external_id','Venda'],['sold_on','Data'],['product','Produto'],['quantity','Unidades'],['revenue','Receita'],['cmv','CMV'],['tax','Impostos'],['card','Cartão'],['commission','Comissão'],['installments','Parcelas']]:(fields[table]||[]).map(f=>[f.key,f.label]);
 const currency=new Set(['revenue','cmv','tax','card','commission','amount','paid',...(area==='payables'?['balance']:[])]);
 function open(row:Row|null=null){setEdit(row);setError('');dialog.current?.showModal()}
 return <section className="operations-page" aria-busy={loading}><div className="operations-actions"><span className="eyebrow">{area==='payment_terms'?'CONFIGURAÇÕES DA EMPRESA':'CONTROLE DA OPERAÇÃO'}</span><div>{area==='payment_terms'&&<a href="#/workspace/settings">Voltar às configurações</a>}{area==='payables'&&<a className="import-action" href="#/workspace/bill_payments">Pagar conta</a>}<button className="primary-button" onClick={()=>open()} disabled={loading}><Plus size={17}/>{info.action}</button></div></div>
 <div className="catalog-metrics">{metrics.map(([label,value],i)=>{const Icon=[Wallet,TrendingUp,Package,CalendarDays][i];return <article key={label}><span className="catalog-icon"><Icon size={20}/></span><div><strong>{value}</strong><span>{label}</span></div></article>})}</div><p className="operations-hint">{info.hint}</p>{area==='sales'&&<p className="muted">Resultado antes de despesas operacionais e devoluções. Os indicadores acompanham os filtros abaixo.</p>}{notice&&<p className="workspace-notice" role="status">{notice}</p>}{error&&!dialog.current?.open&&<p className="workspace-error" role="alert">{error}</p>}
 <article className="catalog-card"><header><h2>{info.title}</h2><span>{visible.length} de {rows.length}</span></header><div className="operations-filters"><label className="operations-search"><Search size={17}/><input aria-label="Buscar nesta tabela" placeholder={area==='inventory'?'Buscar produto ou SKU…':area==='payment_terms'?'Buscar condição…':'Buscar por referência, nome…'} value={query} onChange={e=>setQuery(e.target.value)}/></label>{dated&&<><label>De<input type="date" value={from} max={to||undefined} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input type="date" value={to} min={from||undefined} onChange={e=>setTo(e.target.value)}/></label></>}{['inventory','payables','stock_movements','sales','bills'].includes(area)&&<label>{area==='inventory'?'Saldo':area==='payables'?'Situação':area==='stock_movements'?'Filtrar movimento':'Filtrar categoria'}<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todos</option>{(area==='inventory'?[['empty','Sem saldo'],['available','Com saldo']]:area==='payables'?[['pending','Pendente'],['overdue','Vencido'],['paid','Pago']]:area==='stock_movements'?[['in','Entrada'],['out','Saída']]:[...new Set(rows.map(r=>r.category))].map(c=>[c,c])).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>}{(query||filter||from||to)&&<button onClick={()=>{setQuery('');setFilter('');setFrom('');setTo('')}}>Limpar filtros</button>}</div>
 {loading?<p role="status" className="operations-hint">Carregando…</p>:<div className="workspace-table" role="region" aria-label={info.title} tabIndex={0}><table><thead><tr>{columns.map(([key,label])=><th key={key}>{label}</th>)}{area==='payment_terms'&&<th>Ações</th>}</tr></thead><tbody>{visible.map(r=><tr key={r.id||r.sku}>{columns.map(([key])=><td key={key}>{key==='status'||key==='direction'?<span className={'operation-status '+(r[key]==='overdue'?'danger':'')}>{labels[r[key]]||r[key]}</span>:currency.has(key)?money(r[key]):key.endsWith('_on')?dateLabel(r[key]):String(r[key]??'')}</td>)}{area==='payment_terms'&&<td><button aria-label={'Editar '+r.name} onClick={()=>open(rows.find(x=>x.id===r.id)!)}>Editar</button></td>}</tr>)}</tbody></table>{!visible.length&&<div className="empty-state"><Package size={28}/><h3>{rows.length?'Nenhum resultado para os filtros':'Comece seu controle por aqui'}</h3><p>{rows.length?'Ajuste a busca ou o período para consultar outros registros.':'Use '+info.action.toLowerCase()+' para incluir o primeiro lançamento.'}</p></div>}</div>}</article>
 <dialog className="catalog-dialog operations-dialog" ref={dialog} aria-labelledby="operation-title" onCancel={e=>{if(busy)e.preventDefault()}}><form className="catalog-form" key={edit?.id||'new'} onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,values=new FormData(form),body:Row={};for(const f of fields[table]){const value=String(values.get(f.key)||'');body[f.key]=f.money?Math.round(Number(value)*100):f.type==='number'?Number(value):value}setBusy(true);setError('');try{await request(base+'/records/'+table+(edit?'/'+edit.id:''),{method:edit?'PATCH':'POST',body:JSON.stringify(body)});dialog.current?.close();setEdit(null);form.reset();setVersion(v=>v+1);setNotice('Registro salvo.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><div className="catalog-form-heading"><span className="eyebrow">{edit?'EDITAR':'NOVO LANÇAMENTO'}</span><h2 id="operation-title">{edit?'Editar condição':info.action}</h2><p>{info.hint}</p></div><div className="catalog-fields">{(fields[table]||[]).map(f=><label key={f.key}>{f.label}{f.options?<select name={f.key}>{f.options.map(o=><option value={o} key={o}>{labels[o]||o}</option>)}</select>:f.type==='linked'?<select name={f.key} required defaultValue=""><option value="">Selecione</option>{linked.map(r=><option key={r.id} value={r.id}>{r.sku||r.reference} · {r.name||r.description}</option>)}</select>:<input name={f.key} required type={f.money?'number':f.type||'text'} step={['quantity','installments'].includes(f.key)?1:f.money||f.type==='number'?'0.01':undefined} min={['quantity','installments'].includes(f.key)?1:f.money||f.type==='number'?0:undefined} max={f.key==='installments'?12:f.key==='anticipation_rate'?20:f.key.endsWith('_rate')||f.key==='card_base'?50:undefined} defaultValue={edit?(f.money?edit[f.key]/100:edit[f.key]):f.type==='date'?new Date().toLocaleDateString('en-CA'):['quantity','installments'].includes(f.key)?1:f.money||f.type==='number'?0:''}/>}</label>)}</div>{error&&<p className="workspace-error" role="alert">{error}</p>}<div className="catalog-form-actions"><button type="button" disabled={busy} onClick={()=>dialog.current?.close()}>Cancelar</button><button className="primary-button" disabled={busy}>{busy?'Salvando…':edit?'Salvar alterações':info.save}</button></div></form></dialog>
 </section>
}
