import React,{useEffect,useState} from 'react';
import {DynamicWaterfall} from './FinancialWaterfall';
import {money,Row} from './BusinessPages';
import './control-panel.css';
export function PanelDetails({data}:{data:Row}){
 const [query,setQuery]=useState(''),[negative,setNegative]=useState(false),[sort,setSort]=useState('quantity'),[page,setPage]=useState(0);
 useEffect(()=>setPage(0),[query,negative,sort,data]);
 const t=data.totals,estimated=t.revenue-t.cmv;
 const products=[...(data.products||[])].filter((p:Row)=>(!negative||p.net<0)&&String(p.name).toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))).sort((a:Row,b:Row)=>sort==='loss'?a.net-b.net:sort==='revenue'?b.revenue-a.revenue:b.quantity-a.quantity);
 return <><details className="panel-financial-details"><summary><div><span className="eyebrow">ENTENDA OS NÚMEROS</span><h2>Da receita ao resultado</h2><p>Abra para conferir custos, taxas e devoluções.</p></div><span className="panel-expand" aria-hidden="true">+</span></summary><div className="panel-finance"><article className="workspace-content"><span className="eyebrow">COMPOSIÇÃO FINANCEIRA</span><h3>Composição do resultado</h3><p className="muted">Cada dedução, calculada com os registros do período selecionado.</p><DynamicWaterfall totals={t}/></article><article className="panel-profit"><span className="eyebrow">ALÉM DO FATURAMENTO</span><h2>O que realmente sobra</h2><div><span>Estimativa antes das taxas</span><strong>{money(estimated)}</strong><small>Receita menos custo dos produtos</small></div><div><span>Resultado das vendas</span><strong>{money(t.net)}</strong><small>Após impostos, cartão e comissões</small></div><div className="panel-profit-final"><span>Resultado operacional</span><strong>{money(t.operating)}</strong><small>Após despesas e devoluções, incluindo CMV recuperado. Não representa saldo bancário.</small></div></article></div>
 <div className="panel-deductions">{[['Custo dos produtos','cmv'],['Impostos','tax'],['Cartão','card'],['Comissões','commission'],['Devoluções / estornos','refunds'],['CMV recuperado','cost_recovered']].map(([label,key])=><div key={key}><span>{label}</span><strong>{money(t[key]||0)}</strong></div>)}</div>
 </details><article className="workspace-content panel-products"><div className="panel-section-heading"><div><span className="eyebrow">DESEMPENHO DO CATÁLOGO</span><h2>Produtos e margens</h2><p className="muted">Compare o volume vendido e o resultado de cada produto no período.</p></div><a href="#/workspace/sales">Consultar vendas →</a></div><div className="panel-product-filters"><label>Buscar produto<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome do produto"/></label><label className="check-label"><input type="checkbox" checked={negative} onChange={e=>setNegative(e.target.checked)}/> Somente com prejuízo</label><label>Ordenar por<select value={sort} onChange={e=>setSort(e.target.value)}><option value="quantity">Mais vendidos</option><option value="revenue">Maior receita</option><option value="loss">Menor resultado</option></select></label><span>{products.length} resultados</span></div><div className="workspace-table" role="region" tabIndex={0} aria-label="Desempenho de produtos"><table><thead><tr><th>Produto</th><th>Unidades</th><th>Receita</th><th>Resultado das vendas</th><th>Margem</th></tr></thead><tbody>{products.slice(page*8,page*8+8).map((p:Row,i:number)=><tr key={i}><td>{p.name}</td><td>{p.quantity}</td><td>{money(p.revenue)}</td><td><span className={p.net<0?'panel-loss':''}>{money(p.net)}</span></td><td>{Number(p.margin||0).toLocaleString('pt-BR',{maximumFractionDigits:1})}%</td></tr>)}</tbody></table>{!products.length&&<div className="empty-state"><h3>{query||negative?'Nenhum produto corresponde ao filtro':'Nenhuma venda neste período'}</h3><p>{query||negative?'Ajuste os filtros para consultar os outros resultados.':'Importe ou registre vendas para acompanhar as margens.'}</p></div>}</div>{products.length>8&&<div className="panel-pagination"><span>Página {page+1} de {Math.ceil(products.length/8)}</span><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Anterior</button><button disabled={(page+1)*8>=products.length} onClick={()=>setPage(p=>p+1)}>Próxima</button></div>}</article></>
}
