import React,{useState} from 'react';
import {DynamicWaterfall} from './FinancialWaterfall';
import {money,Row} from './BusinessPages';
import './control-panel.css';
export function PanelDetails({data}:{data:Row}){
 const [query,setQuery]=useState(''),[negative,setNegative]=useState(false);
 const t=data.totals,estimated=t.revenue-t.cmv;
 const products=[...(data.products||[])].filter((p:Row)=>(!negative||p.net<0)&&String(p.name).toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))).sort((a:Row,b:Row)=>b.quantity-a.quantity);
 return <><div className="panel-finance"><article className="workspace-content"><span className="eyebrow">COMPOSIÇÃO FINANCEIRA</span><h2>Da receita ao resultado</h2><p className="muted">Cada dedução, calculada com os registros do período selecionado.</p><DynamicWaterfall totals={t}/></article><article className="panel-profit"><span className="eyebrow">ALÉM DO FATURAMENTO</span><h2>O que realmente sobra</h2><div><span>Estimativa antes das taxas</span><strong>{money(estimated)}</strong><small>Receita menos custo dos produtos</small></div><div><span>Resultado das vendas</span><strong>{money(t.net)}</strong><small>Após impostos, cartão e comissões</small></div><div className="panel-profit-final"><span>Resultado operacional</span><strong>{money(t.operating)}</strong><small>Após despesas e devoluções, incluindo CMV recuperado. Não representa saldo bancário.</small></div></article></div>
 <div className="panel-deductions">{[['Custo dos produtos','cmv'],['Impostos','tax'],['Cartão','card'],['Comissões','commission'],['Devoluções / estornos','refunds'],['CMV recuperado','cost_recovered']].map(([label,key])=><div key={key}><span>{label}</span><strong>{money(t[key]||0)}</strong></div>)}</div>
 <article className="workspace-content panel-products"><div className="panel-section-heading"><div><span className="eyebrow">DESEMPENHO DO CATÁLOGO</span><h2>Produtos e margens</h2><p className="muted">Do maior volume vendido ao menor, conforme os agrupamentos do período.</p></div><a href="#/workspace/sales">Consultar vendas →</a></div><div className="panel-product-filters"><label>Buscar produto<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome do produto"/></label><label className="check-label"><input type="checkbox" checked={negative} onChange={e=>setNegative(e.target.checked)}/> Somente com prejuízo</label><span>{products.length} resultados</span></div><div className="workspace-table" role="region" tabIndex={0} aria-label="Desempenho de produtos"><table><thead><tr><th>Produto</th><th>Unidades</th><th>Receita</th><th>Resultado das vendas</th><th>Margem</th></tr></thead><tbody>{products.map((p:Row,i:number)=><tr key={i}><td>{p.name}</td><td>{p.quantity}</td><td>{money(p.revenue)}</td><td><span className={p.net<0?'panel-loss':''}>{money(p.net)}</span></td><td>{Number(p.margin||0).toLocaleString('pt-BR',{maximumFractionDigits:1})}%</td></tr>)}</tbody></table>{!products.length&&<div className="empty-state"><h3>{query||negative?'Nenhum produto corresponde ao filtro':'Nenhuma venda neste período'}</h3><p>{query||negative?'Ajuste os filtros para consultar os outros resultados.':'Importe ou registre vendas para acompanhar as margens.'}</p></div>}</div></article></>
}
