import React, {useEffect, useState} from 'react';
import {Settings, LogOut, Menu, X, ChevronRight, ShieldCheck, Building2, UserRound, ChartNoAxesCombined, Package, ShoppingBag, Wallet, Boxes, Upload, FileText, ListTodo, Users, Plug, Search} from 'lucide-react';
import {Login} from './Login';
import {createInternalNeonAuth} from '@neondatabase/auth';
const makeAuth = (url:string) => {
 const core=createInternalNeonAuth(url);
 return {getSession:()=>core.adapter.getSession(),signIn:core.adapter.signIn,signUp:core.adapter.signUp,
  signOut:()=>core.adapter.signOut(),getAccessToken:async()=>{
   // A Better Auth session token may be opaque. Ask the JWT plugin explicitly
   // for the signed token that our API verifies against the provider's JWKS.
   // SDK 0.5.0-beta also routes adapter.token() through its get-session cache.
   // Fetch the JWT endpoint directly so a cached session cannot replace it.
   const response=await fetch(url.replace(/\/$/,'')+'/token',{credentials:'include',cache:'no-store'});
   if(response.status===401)return null;
   if(!response.ok)throw Error('Não foi possível validar sua sessão. Tente novamente.');
   const data=await response.json();
   return typeof data.token==='string'?data.token:null;
  }};
};
type AuthClient = ReturnType<typeof makeAuth>;
type AuthSession = {user: {id: string; email: string}};
import './workspace.css';
import './login.css';
import './business.css';
import './premium.css';
import {Integrations,Backups} from './IntegrationPages';
import {Analysis,History,ImportCenter} from './BusinessPages';

type Row = Record<string, any>;
const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100);
const today=()=>new Date().toLocaleDateString('en-CA');
const areas:Record<string,string>={integrations:'Integrações',backups:'Backups',analysis:'Análises',plans:'Planos de ação',customers:'Clientes',dashboard:'Visão geral',products:'Produtos',sales:'Vendas',expenses:'Despesas',adjustments:'Devoluções',settlements:'Recebimentos',reconciliation:'Conciliação',payment_terms:'Condições',imports:'Importações',reports:'Relatórios',report_schedules:'Agendamentos',inventory:'Estoque',stock_movements:'Movimentar estoque',payables:'Contas a pagar',bills:'Cadastrar conta',bill_payments:'Pagar conta',bank_imports:'Importar recebimentos'};
type Field={key:string;label:string;type?:string;money?:boolean;options?:string[]};
const fields:Record<string,Field[]>={
 stock_movements:[{key:'product_id',label:'Produto',type:'linked'},{key:'occurred_on',label:'Data',type:'date'},{key:'direction',label:'Movimento',options:['in','out']},{key:'quantity',label:'Quantidade',type:'number'},{key:'reference',label:'Referência única'},{key:'description',label:'Motivo'}],
 bills:[{key:'reference',label:'Referência única'},{key:'supplier',label:'Fornecedor'},{key:'description',label:'Descrição'},{key:'category',label:'Categoria'},{key:'incurred_on',label:'Competência',type:'date'},{key:'due_on',label:'Vencimento',type:'date'},{key:'amount',label:'Valor (R$)',money:true}],
 bill_payments:[{key:'bill_id',label:'Conta',type:'linked'},{key:'reference',label:'Referência do pagamento'},{key:'paid_on',label:'Data do pagamento',type:'date'},{key:'amount',label:'Valor pago (R$)',money:true}],
 products:[{key:'sku',label:'SKU'},{key:'name',label:'Produto'},{key:'category',label:'Categoria'},{key:'unit_cost',label:'Custo unitário (R$)',money:true},{key:'unit_price',label:'Preço unitário (R$)',money:true}],
 sales:[{key:'external_id',label:'Identificador único da venda'},{key:'sold_on',label:'Data',type:'date'},{key:'product',label:'Produto'},{key:'category',label:'Categoria'},{key:'quantity',label:'Quantidade',type:'number'},...['revenue','cmv','tax','card','commission'].map((key,i)=>({key,label:['Receita total (R$)','CMV total (R$)','Imposto total (R$)','Cartão total (R$)','Comissão total (R$)'][i],money:true})),{key:'installments',label:'Parcelas',type:'number'}],
 expenses:[{key:'description',label:'Descrição'},{key:'category',label:'Categoria'},{key:'incurred_on',label:'Competência',type:'date'},{key:'amount',label:'Valor (R$)',money:true}],
 adjustments:[{key:'sale_id',label:'Venda',type:'sale'},{key:'occurred_on',label:'Data',type:'date'},{key:'kind',label:'Tipo',options:['refund','chargeback']},{key:'amount',label:'Valor devolvido (R$)',money:true},{key:'cost_recovered',label:'CMV recuperado (R$)',money:true},{key:'description',label:'Motivo'}],
 settlements:[{key:'sale_id',label:'Venda',type:'sale'},{key:'reference',label:'Identificador bancário único'},{key:'received_on',label:'Recebido em',type:'date'},{key:'amount',label:'Valor recebido (R$)',money:true}],
 payment_terms:[{key:'name',label:'Condição'},{key:'installments',label:'Parcelas',type:'number'},...['tax_rate','commission_rate','card_base','anticipation_rate'].map((key,i)=>({key,label:['Imposto (%)','Comissão (%)','Cartão / MDR (%)','Antecipação (% a.m.)'][i],type:'number'}))],
 report_schedules:[{key:'period',label:'Periodicidade',options:['daily','weekly','monthly']}]
};
const translations:Record<string,string>={in:'Entrada',out:'Saída',paid:'Pago',overdue:'Vencido',daily:'Diário',weekly:'Semanal',monthly:'Mensal',refund:'Devolução',chargeback:'Estorno',reconciled:'Conciliado',pending:'Pendente',excess:'Recebido a maior'};
export function Workspace(){
 const [client,setClient]=useState<AuthClient|null>(null),[session,setSession]=useState<AuthSession|null>(null);
 const [ready,setReady]=useState(false),[error,setError]=useState('');
 const [companies,setCompanies]=useState<Row[]>([]),[company,setCompany]=useState('');
 const [area,setArea]=useState(location.hash.split('/')[2]||'dashboard');
 const [menuOpen,setMenuOpen]=useState(false);
 const [companiesLoaded,setCompaniesLoaded]=useState(false);
 const [version,setVersion]=useState(0),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{let alive=true;fetch('/api/config').then(r=>r.json()).then(async c=>{if(!alive)return;if(c.configured){const auth=makeAuth(c.neon_auth_url);setClient(auth);const {data}=await auth.getSession();if(alive)setSession(data)}setReady(true)}).catch(()=>{setError('Não foi possível consultar a configuração.');setReady(true)});return()=>{alive=false}},[]);
 useEffect(()=>{if(!client)return;let alive=true;const refresh=()=>{client.getSession().then(({data})=>{if(alive)setSession(data)}).catch(()=>{if(alive)setSession(null)})};window.addEventListener('focus',refresh);return()=>{alive=false;window.removeEventListener('focus',refresh)}},[client]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenuOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
 useEffect(()=>{if(!session){setCompanies([]);setCompany('');setCompaniesLoaded(false)}},[session?.user.id]);
 useEffect(()=>{const changed=()=>setArea(location.hash.split('/')[2]||'dashboard');window.addEventListener('hashchange',changed);return()=>window.removeEventListener('hashchange',changed)},[]);
 async function request(path:string,init:RequestInit={}){
   const token=await client!.getAccessToken();
   if(!token){setSession(null);throw Error('Sua sessão expirou. Entre novamente.');}
   const r=await fetch('/api/workspace'+path,{...init,headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`,...init.headers}});
   if(!r.ok){if(r.status===401){setSession(null);setError('Sua sessão expirou. Entre novamente.')}const data=await r.json().catch(()=>({detail:'Serviço indisponível.'}));throw Error(typeof data.detail==='string'?data.detail:'Confira os campos informados.')}
   return r;
 }
 useEffect(()=>{if(!session)return;let active=true;request('/companies').then(r=>r.json()).then(rows=>{if(active){setCompanies(rows);setCompany(previous=>{const saved=previous||localStorage.getItem('lucra-company:'+session.user.id);return rows.some((r:Row)=>r.id===saved)?saved:rows[0]?.id||''});setCompaniesLoaded(true)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[session?.user.id,version]);
 useEffect(()=>{if(session&&company)localStorage.setItem('lucra-company:'+session.user.id,company)},[session?.user.id,company]);
 async function auth(mode:'login'|'signup',email:string,password:string) {setBusy(true);setError('');setNotice('');try{const {error}=mode==='login'?await client!.signIn.email({email,password}):await client!.signUp.email({email,password,name:email.split('@')[0]});if(error)throw Error((error.code==='INVALID_ORIGIN'||error.message?.toLowerCase()==='invalid origin')?'Este endereço ainda não está autorizado para entrar ou criar conta. Entre em contato com o suporte.':error.message||'Falha na autenticação.');const current=await client!.getSession();setSession(current.data);if(current.data)location.hash='/workspace/dashboard';if(mode==='signup')setNotice('Conta solicitada. Confira seu e-mail para confirmar o acesso.')}catch(e){setError((e as Error).message?.toLowerCase()==='invalid origin'?'Este endereço ainda não está autorizado para entrar ou criar conta. Entre em contato com o suporte.':(e as Error).message)}finally{setBusy(false)}}
 if(!ready)return <main className="workspace-app"><p role="status">Carregando área da empresa…</p></main>;
 if(!client)return <main className="workspace-app setup-panel"><a href="#/demo/overview">← Ver demonstração</a><h1>Conecte sua empresa</h1><p>Para cadastrar e manter seus dados, configure o projeto Neon no servidor e aplique as migrações do banco.</p><p>A conexão PostgreSQL e a URL do Neon Auth ainda não estão configuradas neste ambiente. Nenhum dado real será salvo no modo demonstrativo.</p>{error&&<p role="alert">{error}</p>}</main>;
 async function signOut(){setBusy(true);setError('');try{const result=await client!.signOut();if(result.error)throw Error(result.error.message||'Falha ao sair.');setSession(null);setCompanies([]);setCompany('');setCompaniesLoaded(false);setNotice('');setMenuOpen(false);location.hash='/login'}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!session)return <Login busy={busy} error={error} notice={notice} onSubmit={auth}/>;
 const navigation:Record<string,string>={...areas,settings:'Configurações'};
 const groups=[{label:'VISÃO E ESTRATÉGIA',items:[['analysis',ChartNoAxesCombined],['plans',ListTodo]]},{label:'OPERAÇÃO',items:[['products',Package],['sales',ShoppingBag],['payables',Wallet],['inventory',Boxes],['customers',Users]]},{label:'DADOS E DOCUMENTOS',items:[['imports',Upload],['integrations',Plug],['reports',FileText],['settings',Settings]]}];
 const related=[['analysis','dashboard'],['products','payment_terms'],['sales','adjustments','settlements','reconciliation'],['payables','expenses','bills','bill_payments'],['inventory','stock_movements'],['imports','integrations','backups','bank_imports'],['reports','report_schedules']].find(g=>g.includes(area))||[];
 const descriptions:Record<string,string>={products:'Seu catálogo, custos e preços em um só lugar.',sales:'Acompanhe as vendas e os custos de cada negociação.',expenses:'Organize os gastos que fazem parte da operação.',payables:'Saiba o que pagar, quanto falta e quando vence.',inventory:'Confira o saldo e registre as movimentações dos produtos.',reports:'Transforme os registros em relatórios para acompanhar e compartilhar.',dashboard:'Confira os números do período e a formação do resultado.',settings:'Gerencie sua conta, empresa ativa e condições de venda.'};

 return <div className="workspace-app workspace-layout">
 <a className="workspace-skip" href="#workspace-main" onClick={e=>{e.preventDefault();document.getElementById("workspace-main")?.focus()}}>Pular para o conteúdo</a>
 {menuOpen&&<button className="workspace-backdrop" aria-label="Fechar menu" onClick={()=>setMenuOpen(false)}/>}
 <aside className={'workspace-sidebar'+(menuOpen?' is-open':'')} aria-label="Menu principal">
 <a className="workspace-logo" href="#/workspace/dashboard" aria-label="Lucra — visão geral"><img className="lucra-logo" src="/brand/lucra-dark.svg" width="144" height="32" alt="Lucra"/></a>
 <a className="company-badge" href="#/workspace/settings"><span className="company-avatar"><Building2 size={20}/></span><span><small>EMPRESA ATIVA</small><strong>{companies.find(c=>c.id===company)?.name||'Sua empresa'}</strong></span><ChevronRight size={15}/></a>
 <nav className="workspace-nav" aria-label="Área da empresa">{groups.map(group=><div className="nav-group" key={group.label}><span className="workspace-nav-label">{group.label}</span>{group.items.map(([key,Icon])=>{const id=key as string;const Symbol=Icon as typeof Settings;const active=area===id||(id==='analysis'&&area==='dashboard')||(id==='payables'&&['expenses','bills','bill_payments'].includes(area))||(id==='sales'&&['adjustments','settlements','reconciliation'].includes(area))||(id==='inventory'&&area==='stock_movements')||(id==='imports'&&area==='bank_imports')||(id==='integrations'&&area==='backups')||(id==='reports'&&area==='report_schedules')||(id==='products'&&area==='payment_terms');return <a key={id} href={'#/workspace/'+id} onClick={()=>setMenuOpen(false)} aria-current={active?'page':undefined}><Symbol size={18}/><span>{navigation[id]}</span>{id==='analysis'&&<small className="nav-new" aria-hidden="true">NOVO</small>}</a>})}</div>)}</nav>
 <div className="workspace-account"><span className="workspace-account-avatar"><UserRound size={20}/></span><div><strong>Minha conta</strong><small>{session.user.email}</small></div></div>
 <button className="workspace-signout" onClick={signOut} disabled={busy}><LogOut size={18}/>{busy?'Aguarde…':'Sair da conta'}</button>
 </aside>
 <div className="workspace-body"><header className="workspace-header"><button className="workspace-menu-toggle" aria-label={menuOpen?'Fechar navegação':'Abrir navegação'} aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X size={22}/>:<Menu size={22}/>}</button><span>Minha empresa <ChevronRight size={14}/> <b>{navigation[area]||'Visão geral'}</b></span><span className="workspace-private"><ShieldCheck size={15}/> Área privada</span></header>
 <main id="workspace-main" tabIndex={-1}><div className="page-heading"><div><span className="eyebrow">{companies.find(c=>c.id===company)?.name||'BEM-VINDO AO LUCRA'}</span><h1>{navigation[area]||'Área da empresa'}</h1>{descriptions[area]&&<p>{descriptions[area]}</p>}</div>{company&&['products','sales','expenses'].includes(area)&&<a className="import-action" href="#/workspace/imports"><Upload size={17}/> Importar planilha</a>}</div>{related.length>1&&<nav className="section-tabs" aria-label="Operações desta área">{related.map(id=><a key={id} href={'#/workspace/'+id} aria-current={area===id?'page':undefined}>{areas[id]}</a>)}</nav>}{error&&<p role="alert" className="workspace-error">{error}</p>}{companiesLoaded&&(area==='settings'||!companies.length)&&<details open={!companies.length}><summary>{companies.length?'Cadastrar outra empresa':'Vamos cadastrar sua empresa'}</summary><p>Este cadastro é feito uma vez. Depois, o Lucra abre sua empresa automaticamente.</p><form className="workspace-inline" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const name=new FormData(form).get('name');setBusy(true);try{const created=await (await request('/companies',{method:'POST',body:JSON.stringify({name})})).json();setCompany(created.id);setVersion(v=>v+1);form.reset();setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Nome da empresa<input name="name" required minLength={2} maxLength={120}/></label><button className="primary-button" disabled={busy}>Criar empresa</button></form></details>}
 {!companiesLoaded?<p role="status">Carregando sua empresa…</p>:area==='settings'?<section className="workspace-settings"><article><UserRound size={23}/><h2>Minha conta</h2><p>Seu acesso ao Lucra.</p><label>E-mail da conta<input readOnly value={session.user.email}/></label><p className="settings-caption">Use uma conta própria para cada cliente. Seus dados são associados ao proprietário da empresa.</p></article><article><Building2 size={23}/><h2>Sua empresa</h2><p>{companies.find(c=>c.id===company)?.name||'Crie ou selecione uma empresa para começar.'}</p><p>A empresa ativa é lembrada neste navegador. A troca fica disponível aqui para contas com mais de uma empresa.</p>{companies.length>1&&<label>Trocar empresa<select value={company} onChange={e=>setCompany(e.target.value)}>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}{company&&<a className="settings-action" href="#/workspace/payment_terms">Configurar taxas e parcelamento <ChevronRight size={16}/></a>}</article><article><ShieldCheck size={23}/><h2>Privacidade e acesso</h2><a className="settings-action" href="#/workspace/backups">Backups da empresa <ChevronRight size={16}/></a><p>Os registros são restritos às empresas da sua conta. Ao usar um computador compartilhado, encerre a sessão quando terminar.</p><button onClick={signOut} disabled={busy}><LogOut size={16}/> Sair da conta</button></article></section>:company?<React.Fragment key={company+area}>{area==='integrations'?<Integrations base={'/'+company} request={request}/>:area==='backups'?<Backups base={'/'+company} request={request}/>:area==='analysis'?<Analysis base={'/'+company} request={request}/>:area==='plans'||area==='customers'?<History base={'/'+company} request={request} customers={area==='customers'}/>:area==='imports'?<ImportCenter base={'/'+company} request={request}/>:<CompanyArea company={company} area={area} request={request}/>}</React.Fragment>:<p>Crie ou selecione uma empresa para começar.</p>}</main><footer>Dados da sua empresa · valores financeiros em reais na interface</footer></div></div>
}
type Requester=(path:string,init?:RequestInit)=>Promise<Response>;
function CompanyArea({company,area,request}:{company:string;area:string;request:Requester}){
 const [rows,setRows]=useState<Row[]>([]),[sales,setSales]=useState<Row[]>([]),[linked,setLinked]=useState<Row[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
 const [period,setPeriod]=useState('monthly'),[anchor,setAnchor]=useState(today()),[summary,setSummary]=useState<Row|null>(null);
 const [csv,setCsv]=useState(''),[preview,setPreview]=useState<Row|null>(null),[edit,setEdit]=useState<Row|null>(null);
 const base='/'+company;
 useEffect(()=>{let alive=true;setBusy(true);setError('');const endpoint=area==='dashboard'?`/dashboard?period=${period}&anchor=${anchor}`:area==='reports'?'/reports':area==='reconciliation'?'/reconciliation':area==='inventory'?'/inventory':area==='payables'?'/payables':fields[area]?'/records/'+area:null;
 const work=endpoint?request(base+endpoint).then(r=>r.json()).then(data=>{if(alive){if(area==='dashboard')setSummary(data);else setRows(data)}}):Promise.resolve();
 work.catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setBusy(false)});
 if(area==='stock_movements'||area==='bill_payments')request(base+'/records/'+(area==='stock_movements'?'products':'bills')).then(r=>r.json()).then(data=>{if(alive)setLinked(data)}).catch(e=>{if(alive)setError(e.message)});
 if(area==='adjustments'||area==='settlements')request(base+'/records/sales').then(r=>r.json()).then(s=>{if(alive)setSales(s)}).catch(e=>{if(alive)setError(e.message)});
 return()=>{alive=false}},[area,company,period,anchor,version]);
 async function action(work:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await work()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function download(id:string){const r=await request(base+'/reports/'+id+'/pdf');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`lucra-${id}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const periodControls=<div className="workspace-inline"><label>Período<select value={period} onChange={e=>setPeriod(e.target.value)}>{['daily','weekly','monthly'].map(p=><option key={p} value={p}>{translations[p]}</option>)}</select></label><label>Data de referência<input type="date" required value={anchor} onChange={e=>{if(e.target.value)setAnchor(e.target.value)}}/></label></div>;
 return <section className="workspace-content" aria-busy={busy}>{error&&<p role="alert" className="workspace-error">{error}</p>}{notice&&<p role="status" className="workspace-notice">{notice}</p>}{busy&&<p role="status">Processando…</p>}
 {area==='dashboard'&&<>{periodControls}{summary&&<><p>{summary.company} · {summary.start} a {summary.end}</p><div className="workspace-metrics">{[['Faturamento','revenue'],['Resultado das vendas','net'],['Despesas operacionais','expenses'],['Devoluções / estornos','refunds'],['CMV recuperado','cost_recovered'],['Resultado operacional','operating']].map(([label,key])=><article key={key}><span>{label}</span><strong>{brl(summary.totals[key])}</strong></article>)}</div><h2>Da receita ao resultado</h2><DynamicWaterfall totals={summary.totals}/><p>Resultado operacional = resultado das vendas − despesas − devoluções + CMV recuperado. Não representa saldo bancário.</p><DataTable rows={summary.products} columns={[['name','Produto'],['quantity','Unidades'],['revenue','Receita'],['net','Resultado'],['margin','Margem (%)']]}/></>}</>}
 {area==='inventory'&&<><p>Saldo dos movimentos registrados. Registre entradas iniciais e saídas; cadastrar uma venda não altera automaticamente o estoque.</p><DataTable rows={rows} columns={[["sku","SKU"],["name","Produto"],["balance","Saldo em unidades"]]}/></>}
 {area==='payables'&&<><p>Contas ordenadas por vencimento. O cadastro reconhece a despesa na competência; o pagamento reduz a dívida sem duplicar a despesa.</p><DataTable rows={rows} moneyKeys={['amount','paid','balance']} columns={[["reference","Referência"],["supplier","Fornecedor"],["due_on","Vencimento"],["amount","Valor"],["paid","Pago"],["balance","Saldo"],["status","Situação"]]}/></>}
 {area==='bank_imports'&&<BankImport request={request} base={base}/>}
 {fields[area]&&<><div className="ledger-summary"><article><span>Registros cadastrados</span><strong>{rows.length}</strong></article><article><span>{area==='products'?'Produtos ativos':area==='sales'?'Receita registrada':area==='expenses'||area==='bills'?'Valor registrado':'Nesta área'}</span><strong>{area==='products'?rows.filter(r=>r.active).length:area==='sales'?brl(rows.reduce((v,r)=>v+r.revenue,0)):area==='expenses'||area==='bills'?brl(rows.reduce((v,r)=>v+r.amount,0)):areas[area]}</strong></article><article><span>Organização</span><strong>{new Set(rows.map(r=>r.category).filter(Boolean)).size||'—'}</strong><small>Categorias nos registros</small></article></div><p>{area==='bills'?'Ao cadastrar esta conta, uma despesa é registrada automaticamente. Não lance novamente o mesmo valor na tela Despesas.':area==='bill_payments'?'Registre baixas parciais ou totais. O banco bloqueia pagamentos acima do saldo.':area==='stock_movements'?'Movimentos são imutáveis. Para corrigir, registre o movimento inverso com outra referência. Saídas acima do saldo são bloqueadas.':area==='sales'?'Informe totais por venda, incluindo impostos e taxas efetivamente cobrados. O identificador impede duplicidades.':area==='report_schedules'?'Os relatórios são enviados somente ao e-mail confirmado da sua conta, após o encerramento do período. O serviço de envio precisa estar configurado no servidor.':area==='settlements'?'Registre cada crédito recebido com sua referência bancária. A conciliação compara recebimentos com a receita menos cartão e devoluções.':area==='adjustments'?'Devoluções são registradas na data em que ocorreram. O CMV recuperado não pode exceder o custo original.':'Cadastros vinculados somente à empresa selecionada.'}</p>
 <details className="record-create" open={edit?true:undefined}><summary>{edit?'Editar registro':'Adicionar registro'}</summary><form key={edit?.id||'new'} className="workspace-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const values=new FormData(form);const body:Row={};for(const f of fields[area]){const value=String(values.get(f.key)||'');body[f.key]=f.money?Math.round(Number(value)*100):f.type==='number'?Number(value):value}if(area==='products')body.active=values.get('active')==='on';if(area==='report_schedules')body.enabled=values.get('enabled')==='on';action(async()=>{await request(base+'/records/'+area+(edit?'/'+edit.id:''),{method:edit?'PATCH':'POST',body:JSON.stringify(body)});setEdit(null);form.reset();setVersion(v=>v+1);setNotice('Registro salvo.')})}}>
 {fields[area].map(f=><label key={f.key}>{f.label}{f.options?<select name={f.key} defaultValue={edit?.[f.key]||f.options[0]}>{f.options.map(o=><option key={o} value={o}>{translations[o]||o}</option>)}</select>:f.type==='linked'?<select name={f.key} required defaultValue=""><option value="">Selecione</option>{linked.map(r=><option key={r.id} value={r.id}>{r.sku||r.reference} · {r.name||r.description}</option>)}</select>:f.type==='sale'?<select name={f.key} required defaultValue=""><option value="">Selecione uma venda</option>{sales.map(s=><option key={s.id} value={s.id}>{s.external_id} · {s.product}</option>)}</select>:<input name={f.key} required type={f.money?'number':f.type||'text'} min={f.money||f.type==='number'?0:undefined} step={['quantity','installments'].includes(f.key)?'1':f.money||f.type==='number'?'0.01':undefined} defaultValue={edit?(f.money?edit[f.key]/100:edit[f.key]):f.type==='date'?today():f.money?'0':undefined}/>}</label>)}
 {area==='products'&&<label className="check-label"><input type="checkbox" name="active" defaultChecked={edit?edit.active:true}/>Produto ativo</label>}{area==='report_schedules'&&<label className="check-label"><input type="checkbox" name="enabled" defaultChecked={edit?edit.enabled:true}/>Agendamento ativo</label>}
 <div className="workspace-form-actions"><button className="primary-button" disabled={busy}>{edit?'Salvar alterações':'Cadastrar'}</button>{edit&&<button type="button" onClick={()=>setEdit(null)}>Cancelar edição</button>}</div></form></details>
 <div className="table-heading"><h2>Registros de {areas[area]?.toLowerCase()}</h2><span>{rows.length} registros</span></div><DataTable rows={rows.map(row=>{const display={...row};for(const f of fields[area]){if(f.type==='sale')display[f.key]=sales.find(s=>s.id===row[f.key])?.external_id||'Venda';if(f.type==='linked'){const record=linked.find(r=>r.id===row[f.key]);display[f.key]=record?`${record.sku||record.reference} - ${record.name||record.description}`:'Registro vinculado'}}return display})} columns={fields[area].map(f=>[f.key,f.label])} moneyKeys={fields[area].filter(f=>f.money).map(f=>f.key)} onEdit={['products','payment_terms','report_schedules'].includes(area)?setEdit:undefined}/></>}
 {area==='imports'&&<><p>CSV com vírgula como separador, valores em reais com ponto decimal e datas AAAA-MM-DD. Máximo de 1.000 vendas e 2 MB. A confirmação é atômica: um conflito impede todo o lote.</p><button onClick={()=>{const blob=new Blob(['external_id,sold_on,product,category,quantity,revenue,cmv,tax,card,commission,installments\nVENDA-001,2026-09-18,Produto exemplo,Geral,1,200.00,140.00,12.00,23.50,8.00,12\n'],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='modelo-vendas.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Baixar modelo CSV</button><label>Arquivo CSV<input type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];setPreview(null);setCsv('');if(file){if(file.size>2_000_000){setError('Arquivo maior que 2 MB.');return}setCsv(await file.text())}}}/></label><button className="primary-button" disabled={busy||!csv} onClick={()=>action(async()=>{const r=await request(base+'/imports/preview',{method:'POST',body:JSON.stringify({content:csv})});setPreview(await r.json())})}>Validar e visualizar</button>{preview&&<><p>{preview.rows.length} linhas válidas · {preview.errors.length} erros · {preview.duplicates.length} duplicidades existentes.</p>{preview.errors.map((e:Row)=><p key={e.line} role="alert">Linha {e.line}: {e.message}</p>)}{preview.duplicates.length>0&&<p role="alert">Duplicados: {preview.duplicates.join(', ')}</p>}<DataTable rows={preview.rows.slice(0,20)} columns={[['external_id','Identificador'],['sold_on','Data'],['product','Produto'],['revenue','Receita']]}/><p>Prévia das primeiras 20 linhas.</p><button className="primary-button" disabled={busy||!preview.can_import} onClick={()=>action(async()=>{const r=await request(base+'/imports/confirm',{method:'POST',body:JSON.stringify({content:csv})});const data=await r.json();setPreview(null);setCsv('');setNotice(`${data.imported} vendas importadas.`)})}>Confirmar importação</button></>}</>}
 {area==='reconciliation'&&<><p>Conciliação por venda. O esperado considera receita menos cartão e devoluções; impostos e comissões são despesas separadas. Créditos de todas as datas são considerados.</p><DataTable rows={rows} columns={[['external_id','Venda'],['product','Produto'],['expected','Esperado'],['received','Recebido'],['difference','Diferença'],['status','Situação']]}/></>}
 {area==='reports'&&<>{periodControls}<button className="primary-button" disabled={busy} onClick={()=>action(async()=>{const r=await request(base+'/reports',{method:'POST',body:JSON.stringify({period,anchor})});const report=await r.json();setVersion(v=>v+1);await download(report.id);setNotice('Relatório salvo no histórico e download iniciado.')})}>Gerar e salvar PDF</button><h2>Histórico de relatórios</h2><p>Cada relatório preserva os dados usados na geração, mesmo se houver novos lançamentos depois.</p><ul className="report-list">{rows.map(r=><li key={r.id}><span>{translations[r.period]} · {r.anchor} · {new Date(r.created_at).toLocaleString('pt-BR')}</span><button disabled={busy} onClick={()=>action(()=>download(r.id))}>Baixar PDF</button></li>)}</ul>{!rows.length&&<p>Nenhum relatório gerado.</p>}</>}
 </section>
}
function DataTable({rows,columns,moneyKeys=[],onEdit}:{rows:Row[];columns:string[][];moneyKeys?:string[];onEdit?:(r:Row)=>void}){const [query,setQuery]=useState('');const visible=rows.filter(r=>columns.some(([key])=>String(r[key]??'').toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))));const currency=new Set(['revenue','cmv','tax','card','commission','net','expected','received','difference',...moneyKeys]);return <><div className="table-tools"><label><Search size={16}/><input aria-label="Buscar nesta tabela" placeholder="Buscar registros…" value={query} onChange={e=>setQuery(e.target.value)}/></label><span>{visible.length} de {rows.length} registros</span></div><div className="workspace-table" tabIndex={0} role="region" aria-label="Tabela de registros"><table><thead><tr>{columns.map(([key,label])=><th key={key} scope="col">{label}</th>)}{onEdit&&<th scope="col">Ações</th>}</tr></thead><tbody>{visible.map((r,i)=><tr key={r.id||i}>{columns.map(([key])=><td key={key}>{currency.has(key)?brl(Number(r[key])):translations[r[key]]||String(r[key]??'')}</td>)}{onEdit&&<td><button onClick={()=>onEdit(r)}>Editar{r.enabled===false?' (inativo)':r.active===false?' (inativo)':''}</button></td>}</tr>)}</tbody></table>{!visible.length&&<div className="table-empty"><Search size={25}/><strong>{query?'Nenhum resultado encontrado':'Seus registros aparecerão aqui'}</strong><p>{query?'Tente outro termo de busca.':'Adicione um registro ou importe uma planilha para começar.'}</p></div>}</div></>}
export function DynamicWaterfall({totals}:{totals:Record<string,number>}){
 const steps=[['Receita',totals.revenue],['CMV',-totals.cmv],['Impostos',-totals.tax],['Cartão',-totals.card],['Comissões',-totals.commission],['Despesas',-(totals.expenses||0)],['Devoluções',-(totals.refunds||0)],['CMV recuperado',totals.cost_recovered||0]] as [string,number][];
 let current=0;const bars=steps.map(([label,value])=>{const before=current;current+=value;return {label,value,before,after:current}});bars.push({label:'Resultado',value:current,before:0,after:current});
 const low=Math.min(0,...bars.flatMap(b=>[b.before,b.after])),high=Math.max(1,...bars.flatMap(b=>[b.before,b.after]));const y=(v:number)=>190-(v-low)/(high-low)*140;
 return <div className="dynamic-waterfall" tabIndex={0} role="region" aria-label="Gráfico de formação do resultado"><svg viewBox="0 0 810 260" role="img" aria-label={'Cascata do período: '+bars.map(b=>b.label+' '+brl(b.value)).join('; ')}><line x1="10" x2="800" y1={y(0)} y2={y(0)} stroke="#b8c6be"/>{bars.map((b,i)=><g key={b.label}><rect x={12+i*89} y={Math.min(y(b.before),y(b.after))} width="60" height={Math.max(1,Math.abs(y(b.before)-y(b.after)))} rx="3" fill={b.value<0?'#bb6655':'#2a7050'}/><text x={42+i*89} y={Math.min(y(b.before),y(b.after))-9} textAnchor="middle" fontSize="10" fill="#264535">{brl(b.value)}</text><text x={42+i*89} y="222" textAnchor="middle" fontSize="9" fill="#4b6656">{b.label}</text></g>)}</svg></div>
}

function BankImport({request,base}:{request:Requester;base:string}){
 const [content,setContent]=useState(''),[preview,setPreview]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function submit(confirm=false){setBusy(true);setError('');setNotice('');try{const r=await request(base+'/bank-imports/'+(confirm?'confirm':'preview'),{method:'POST',body:JSON.stringify({content})});const data=await r.json();if(confirm){setContent('');setPreview(null);setNotice(`${data.imported} recebimentos conciliados por identificador de venda.`)}else setPreview(data)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section><h2>Importar créditos de extrato</h2><p>Converta o extrato para o modelo abaixo. Cada crédito precisa informar o identificador da venda. Vendas desconhecidas e referências repetidas bloqueiam a importação. Não há conexão automática com bancos.</p><pre tabIndex={0} aria-label="Modelo CSV de recebimentos">reference,external_id,received_on,amount{'\n'}BANCO-001,VENDA-001,2026-09-18,176.50</pre><label>CSV de recebimentos<input type="file" accept=".csv,text/csv" onChange={async e=>{setPreview(null);setContent('');setError('');const file=e.target.files?.[0];if(file){if(file.size>2000000){setError('Arquivo maior que 2 MB.');return}setContent(await file.text())}}}/></label><button disabled={busy||!content} onClick={()=>submit()}>Validar recebimentos</button>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{preview&&<><p>{preview.rows.length} créditos válidos; {preview.errors.length} erros.</p>{preview.errors.map((r:Row)=><p role="alert" key={r.line}>Linha {r.line}: {r.message}</p>)}<DataTable rows={preview.rows.slice(0,20)} columns={[["reference","Referência"],["received_on","Data"],["amount","Valor"]]} moneyKeys={['amount']}/><button disabled={busy||!preview.can_import} onClick={()=>submit(true)}>Confirmar recebimentos</button></>}</section>
}
